# Version for Yuuki Asuna mod

find_package(Git)

set(MOD_BUILD "@ADE")

execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --tags --match=[0-9].[0-9]* HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_HEAD_TAG
    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE X265_HEAD_TAG_RESULT
)

execute_process(
    COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE X265_HEAD_HASH
    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT X265_HEAD_TAG OR X265_HEAD_TAG_RESULT)
    set(X265_VERSION "unknown-g${X265_HEAD_HASH}")
    set(X265_LATEST_TAG "0.0")
    set(X265_TAG_DISTANCE 0)
    message(STATUS "x265 Mod: ${MOD_BUILD}")
    message(STATUS "x265 Release Version: ${X265_VERSION}")
    return()
endif()

string(REPLACE "-" ";" X265_HEAD_TAG_ARR ${X265_HEAD_TAG})
list(LENGTH X265_HEAD_TAG_ARR X265_HEAD_TAG_LEN)

if(X265_HEAD_TAG_LEN LESS 3)
    string(REPLACE "M" "" X265_LATEST_TAG ${X265_HEAD_TAG})
    set(X265_VERSION "${X265_LATEST_TAG}-g${X265_HEAD_HASH}")
    set(X265_TAG_DISTANCE 0)
    message(STATUS "x265 Mod: ${MOD_BUILD}")
    message(STATUS "x265 Release Version: ${X265_VERSION}")
    return()
endif()

list(GET X265_HEAD_TAG_ARR 0 X265_ORIG_TAG)
list(GET X265_HEAD_TAG_ARR 1 X265_HEAD_DISTANCE)

string(REPLACE "M" "" X265_LATEST_TAG ${X265_ORIG_TAG})
set(X265_VERSION "${X265_LATEST_TAG}+${X265_HEAD_DISTANCE}-g${X265_HEAD_HASH}")
set(X265_TAG_DISTANCE ${X265_HEAD_DISTANCE})

message(STATUS "x265 Mod: ${MOD_BUILD}")
message(STATUS "x265 Release Version: ${X265_VERSION}")
