#!/usr/bin/env python3
import argparse
from pathlib import Path


TARGET = Path('source/common/param.cpp')
FORBIDDEN_SNIPPETS = (
    'p->selectiveSAO = atoi(value);',
    'OPT("scenecut-aware-qp") p->bEnableSceneCutAwareQp = atoi(value);',
    'OPT("dup-threshold") p->dupThreshold = atoi(value);',
    'parsed[level] = atoi(number);',
    'p->hmeRange[level] = atoi(number);',
    'OPT("input-depth") svtHevcParam->encoderBitDepth = atoi(value);',
    'OPT("total-frames") svtHevcParam->framesToBeEncoded = atoi(value);',
    'OPT("frames") svtHevcParam->framesToBeEncoded = atoi(value);',
    'OPT("qpmin") svtHevcParam->minQpAllowed = atoi(value);',
    'OPT("qpmax") svtHevcParam->maxQpAllowed = atoi(value);',
    'OPT("rc-lookahead") svtHevcParam->lookAheadDistance = atoi(value);',
    'OPT("keyint") svtHevcParam->intraPeriodLength = atoi(value);',
    'svtHevcParam->qp = atoi(value);',
    'svtHevcParam->targetBitRate = atoi(value);',
    'OPT("svt-search-width") svtHevcParam->searchAreaWidth = atoi(value);',
    'OPT("svt-search-height") svtHevcParam->searchAreaHeight = atoi(value);',
    'OPT("svt-hierarchical-level") svtHevcParam->hierarchicalLevels = atoi(value);',
    'OPT("svt-base-layer-switch-mode") svtHevcParam->baseLayerSwitchMode = atoi(value);',
    'OPT("svt-pred-struct") svtHevcParam->predStructure = (uint8_t)atoi(value);',
    'OPT("master-display") svtHevcParam->useMasteringDisplayColorVolume = (uint8_t)atoi(value);',
    'OPT("nalu-file") svtHevcParam->useNaluFile = (uint8_t)atoi(value);',
    'if (atof(value) < 10)',
    'else if (atoi(value) < 100)',
    'int fps = atoi(value);',
    'p->logLevel = atoi(value);',
    'p->logfLevel = atoi(value);',
    'OPT("frame-threads") p->frameNumThreads = atoi(value);',
    'OPT("total-frames") p->totalFrames = atoi(value);',
    'OPT("ctu") p->maxCUSize = (uint32_t)atoi(value);',
    'OPT("min-cu-size") p->minCUSize = (uint32_t)atoi(value);',
    'OPT("tu-intra-depth") p->tuQTMaxIntraDepth = (uint32_t)atoi(value);',
    'OPT("tu-inter-depth") p->tuQTMaxInterDepth = (uint32_t)atoi(value);',
    'OPT("max-tu-size") p->maxTUSize = (uint32_t)atoi(value);',
    'OPT("ctu") p->maxCUSize = parseOptionUint32Token(value, std::strlen(value), bError);',
    'OPT("min-cu-size") p->minCUSize = parseOptionUint32Token(value, std::strlen(value), bError);',
    'OPT("tu-intra-depth") p->tuQTMaxIntraDepth = parseOptionUint32Token(value, std::strlen(value), bError);',
    'OPT("tu-inter-depth") p->tuQTMaxInterDepth = parseOptionUint32Token(value, std::strlen(value), bError);',
    'OPT("max-tu-size") p->maxTUSize = parseOptionUint32Token(value, std::strlen(value), bError);',
    'OPT("subme") p->subpelRefine = atoi(value);',
    'OPT("merange") p->searchRange = atoi(value);',
    'OPT("max-merge") p->maxNumMergeCand = (uint32_t)atoi(value);',
    'OPT("max-merge") p->maxNumMergeCand = parseOptionUint32Token(value, std::strlen(value), bError);',
    'OPT("lookahead-slices") p->lookaheadSlices = atoi(value);',
    'OPT("temporal-layers") p->bEnableTemporalSubLayers = atoi(value);',
    'OPT("keyint") p->keyframeMax = atoi(value);',
    'OPT("min-keyint") p->keyframeMin = atoi(value);',
    'OPT("rc-lookahead") p->lookaheadDepth = atoi(value);',
    'OPT("bframes") p->bframes = atoi(value);',
    'OPT("bframe-bias") p->bFrameBias = atoi(value);',
    'p->scenecutThreshold = atoi(value);',
    'p->bFrameAdaptive = atoi(value);',
    'p->interlaceMode = atobool(value);',
    'p->interlaceMode = parseName(value, x265_interlace_names, bError);',
    'OPT("ref") p->maxNumReferences = atoi(value);',
    'OPT("limit-refs") p->limitReferences = atoi(value);',
    'OPT("cbqpoffs") p->cbQpOffset = atoi(value);',
    'OPT("crqpoffs") p->crQpOffset = atoi(value);',
    'OPT("rd") p->rdLevel = atoi(value);',
    'p->rdoqLevel = atoi(value);',
    'p->psyRd = atof(value);',
    'p->psyRdoq = atof(value);',
    'OPT("psy-bscale") p->psyScaleB = atoi(value);',
    'OPT("psy-pscale") p->psyScaleP = atoi(value);',
    'OPT("psy-iscale") p->psyScaleI = atoi(value);',
    'OPT("hash") p->decodedPictureHashSEI = atoi(value);',
    'OPT("qscale-mode") p->rc.qScaleMode = atoi(value);',
    'OPT("qpstep") p->rc.qpStep = atoi(value);',
    'OPT("aq-mode") p->rc.aqMode = atoi(value);',
    'OPT("qpmax")       p->rc.qpMax = atoi(value);',
    'OPT("qpmin") p->rc.qpMin = atoi(value);',
    'p->rc.bitrate = atoi(value);',
    'p->rc.qp = atoi(value);',
    'OPT("csv-log-level") p->csvLogLevel = atoi(value);',
    'OPT("log2-max-poc-lsb") p->log2MaxPocLsb = atoi(value);',
    'OPT("slices") p->maxSlices = atoi(value);',
    'OPT("limit-tu") p->limitTU = atoi(value);',
    'OPT("lookahead-threads") p->lookaheadThreads = atoi(value);',
    'OPT("analysis-save-reuse-level") p->analysisSaveReuseLevel = atoi(value);',
    'OPT("analysis-load-reuse-level") p->analysisLoadReuseLevel = atoi(value);',
    'OPT("nr-intra") p->noiseReductionIntra = atoi(value);',
    'OPT("nr-inter") p->noiseReductionInter = atoi(value);',
    'OPT("rdpenalty") p->rdPenalty = atoi(value);',
    'OPT("vbv-maxrate") p->rc.vbvMaxBitrate = atoi(value);',
    'OPT("vbv-bufsize") p->rc.vbvBufferSize = atoi(value);',
    'p->vui.chromaSampleLocTypeTopField = atoi(value);',
    'int pass = x265_clip3(0, 3, atoi(value));',
    'OPT("qg-size") p->rc.qgSize = atoi(value);',
    'OPT("min-luma") p->minLuma = (uint16_t)atoi(value);',
    'OPT("max-luma") p->maxLuma = (uint16_t)atoi(value);',
    'OPT("ctu-info") p->bCTUInfo = atoi(value);',
    'OPT("scale-factor") p->scaleFactor = atoi(value);',
    'OPT("refine-intra")p->intraRefine = atoi(value);',
    'OPT("refine-inter")p->interRefine = atoi(value);',
    'OPT("refine-mv")p->mvRefine = atoi(value);',
    'OPT("force-flush")p->forceFlush = atoi(value);',
    'OPT("gop-lookahead") p->gopLookahead = atoi(value);',
    'OPT("radl") p->radl = atoi(value);',
    'OPT("atc-sei") p->preferredTransferCharacteristics = atoi(value);',
    'OPT("pic-struct") p->pictureStructure = atoi(value);',
    'OPT("chunk-start") p->chunkStart = atoi(value);',
    'OPT("chunk-end") p->chunkEnd = atoi(value);',
    'OPT("rskip") p->recursionSkipMode = atoi(value);',
    'OPT("rskip-edge-threshold") p->edgeVarThreshold = atoi(value)/100.0f;',
    'OPT("refine-ctu-distortion") p->ctuDistortionRefine = atoi(value);',
    'p->cpuid = parseCpuName(value, bError, false);',
    'p->format = atoi(value);',
    'p->numViews = atoi(value);',
    'p->bEnableSCC = atoi(value);',
    'OPT("aq-strength") p->rc.aqStrength = atof(value);',
    'OPT("aq-bias-strength") p->rc.aqBiasStrength = atof(value);',
    'OPT("limit-aq1-strength") p->rc.limitAq1Strength = atof(value);',
    'OPT("dynamic-rd") p->dynamicRd = atof(value);',
    'OPT("ipratio") p->rc.ipFactor = atof(value);',
    'OPT("pbratio") p->rc.pbFactor = atof(value);',
    'double qCompress = atof(value);',
    'OPT("cutree-strength") p->rc.cuTreeStrength = atof(value);',
    'OPT("cutree-minqpoffs") p->rc.cuTreeMinQpOffset = atof(value);',
    'OPT("cutree-maxqpoffs") p->rc.cuTreeMaxQpOffset = atof(value);',
    'OPT("cplxblur") p->rc.complexityBlur = atof(value);',
    'OPT("qblur") p->rc.qblur = atof(value);',
    'OPT("vbv-init")    p->rc.vbvBufferInit = atof(value);',
    'OPT("crf-max")     p->rc.rfConstantMax = atof(value);',
    'OPT("crf-min")     p->rc.rfConstantMin = atof(value);',
    'p->rc.rfConstant = atof(value);',
    'OPT("vbv-end") p->vbvBufferEnd = atof(value);',
    'OPT("vbv-end-fr-adj") p->vbvEndFrameAdjust = atof(value);',
    'OPT("max-ausize-factor") p->maxAUSizeFactor = atof(value);',
    'OPT("qp-adaptation-range") p->rc.qpAdaptationRange = atof(value);',
    'OPT("min-vbv-fullness") p->minVbvFullness = atof(value);',
    'OPT("max-vbv-fullness") p->maxVbvFullness = atof(value);',
    'OPT("scenecut-bias") p->scenecutBias = atof(value);',
    'p->rc.zones[i].startFrame = atoi(c);',
    'p->rc.zones[i].endFrame = atoi(firstComma + 1);',
    'p->rc.zones[i].qp = atoi(modeValue);',
    'p->rc.zones[i].bitrateFactor = atof(modeValue);',
    'svtHevcParam->vbvMaxrate = (uint32_t)atoi(value);',
    'svtHevcParam->vbvBufsize = (uint32_t)atoi(value);',
    'svtHevcParam->vbvBufInit = (uint64_t)atof(value);',
    'svtHevcParam->threadCount = (uint32_t)atoi(value);',
)
REQUIRED_SNIPPETS = (
    'static uint8_t parseOptionUint8Token(const char* token, size_t length, bool& bError)',
    'static uint8_t parseOptionUint8Value(const char* value, bool& bError)',
    'static int parseOptionIntValue(const char* value, bool& bError)',
    'static int parseOptionIntValue(const char* value, bool& bError)\n{\n    if (!value)\n    {\n        bError = true;\n        return 0;\n    }',
    'static uint8_t parseOptionUint8Value(const char* value, bool& bError)\n{\n    if (!value)\n    {\n        bError = true;\n        return 0;\n    }',
    'static void assignParsedOptionLevels(const int parsed[3], int count, int target[3])',
    'if (count == 1)\n        target[0] = target[1] = target[2] = parsed[0];',
    'for (int level = 0; level < 3; level++)\n            target[level] = parsed[level];',
    'static uint32_t parseOptionUint32Token(const char* token, size_t length, bool& bError)',
    'static bool parseTenthsOrIntegerLevel(const char* value, int& parsedLevel)',
    'static bool parseFpsValue(const char* value, uint32_t& numerator, uint32_t& denominator)',
    'static bool parseIndexedNameOrNumber(const char* value, const char* const* names, int indexOffset, int& parsedValue)',
    'static bool parseBoolOrIntValue(const char* value, int& parsedValue)',
    'static bool parseBoolOrNamedValue(const char* value, const char* const* names, int& parsedValue)',
    'static bool parseBoolOrNumericInt(const char* value, int falseValue, int& parsedValue)',
    'static bool parseBoolOrNumericDouble(const char* value, double falseValue, double& parsedValue)',
    'int cpuid = parseCpuName(value, bCpuNameError, false);',
    'p->cpuid = cpuid;',
    'int count = splitCommaOption(value, search, searchLengths, 3);',
    'parsed[level] = parseOptionIntToken(search[level], searchLengths[level], bLocalError);',
    'assignParsedOptionLevels(parsed, count, p->hmeSearchMethod);',
    'if (splitCommaOption(value, range, rangeLengths, 3) != 3)',
    'parsed[level] = parseOptionIntToken(range[level], rangeLengths[level], bLocalError);',
    'assignParsedOptionLevels(parsed, 3, p->hmeRange);',
    'int encoderBitDepth = parseOptionIntValue(value, bEncoderBitDepthError);',
    'int framesToBeEncoded = parseOptionIntValue(value, bFramesToBeEncodedError);',
    'int minQpAllowed = parseOptionIntValue(value, bMinQpAllowedError);',
    'int maxQpAllowed = parseOptionIntValue(value, bMaxQpAllowedError);',
    'int lookAheadDistance = parseOptionIntValue(value, bLookAheadDistanceError);',
    'int intraPeriodLength = parseOptionIntValue(value, bIntraPeriodLengthError);',
    'int qp = parseOptionIntValue(value, bQpValueError);',
    'int bitrate = parseOptionIntValue(value, bBitrateValueError);',
    'int searchAreaWidth = parseOptionIntValue(value, bSearchAreaWidthError);',
    'int searchAreaHeight = parseOptionIntValue(value, bSearchAreaHeightError);',
    'int hierarchicalLevels = parseOptionIntValue(value, bHierarchicalLevelsError);',
    'int baseLayerSwitchMode = parseOptionIntValue(value, bBaseLayerSwitchModeError);',
    'int vbvMaxrate = parseOptionIntValue(value, bVbvMaxrateError);',
    'int vbvBufsize = parseOptionIntValue(value, bVbvBufsizeError);',
    'int qScaleMode = parseOptionIntValue(value, bQScaleModeError);',
    'int qpStep = parseOptionIntValue(value, bQpStepError);',
    'int aqMode = parseOptionIntValue(value, bAqModeError);',
    'int rdPenalty = parseOptionIntValue(value, bRdPenaltyError);',
    'int radl = parseOptionIntValue(value, bRadlError);',
    'int parsedPass = parseOptionIntValue(value, bPassError);',
    'int recursionSkipMode = parseOptionIntValue(value, bRecursionSkipModeError);',
    'int subpelRefine = parseOptionIntValue(value, bSubpelRefineError);',
    'int searchRange = parseOptionIntValue(value, bSearchRangeError);',
    'int psyScaleB = parseOptionIntValue(value, bPsyScaleBError);',
    'int psyScaleP = parseOptionIntValue(value, bPsyScalePError);',
    'int psyScaleI = parseOptionIntValue(value, bPsyScaleIError);',
    'int analysisSaveReuseLevel = parseOptionIntValue(value, bAnalysisSaveReuseLevelError);',
    'int analysisLoadReuseLevel = parseOptionIntValue(value, bAnalysisLoadReuseLevelError);',
    'int csvLogLevel = parseOptionIntValue(value, bCsvLogLevelError);',
    'int qpMin = parseOptionIntValue(value, bQpMinError);',
    'int log2MaxPocLsb = parseOptionIntValue(value, bLog2MaxPocLsbError);',
    'int maxSlices = parseOptionIntValue(value, bMaxSlicesError);',
    'int limitTU = parseOptionIntValue(value, bLimitTUError);',
    'int noiseReductionIntra = parseOptionIntValue(value, bNoiseReductionIntraError);',
    'int noiseReductionInter = parseOptionIntValue(value, bNoiseReductionInterError);',
    'int qgSize = parseOptionIntValue(value, bQgSizeError);',
    'int lookaheadThreads = parseOptionIntValue(value, bLookaheadThreadsError);',
    'int ctuInfo = parseOptionIntValue(value, bCTUInfoError);',
    'int scaleFactor = parseOptionIntValue(value, bScaleFactorError);',
    'int intraRefine = parseOptionIntValue(value, bIntraRefineError);',
    'int interRefine = parseOptionIntValue(value, bInterRefineError);',
    'int mvRefine = parseOptionIntValue(value, bMvRefineError);',
    'int forceFlush = parseOptionIntValue(value, bForceFlushError);',
    'int ctuDistortionRefine = parseOptionIntValue(value, bCtuDistortionRefineError);',
    'int decodedPictureHashSEI = parseOptionIntValue(value, bDecodedPictureHashSEIError);',
    'int chromaSampleLocType = parseOptionIntValue(value, bChromaSampleLocTypeError);',
    'int gopLookahead = parseOptionIntValue(value, bGopLookaheadError);',
    'int preferredTransferCharacteristics = parseOptionIntValue(value, bPreferredTransferCharacteristicsError);',
    'int pictureStructure = parseOptionIntValue(value, bPictureStructureError);',
    'int chunkStart = parseOptionIntValue(value, bChunkStartError);',
    'int chunkEnd = parseOptionIntValue(value, bChunkEndError);',
    'int selectiveSao = parseOptionIntValue(value, bSelectiveSaoError);',
    'int dupThreshold = parseOptionIntValue(value, bDupThresholdError);',
    'int format = parseOptionIntValue(value, bFormatError);',
    'int numViews = parseOptionIntValue(value, bNumViewsError);',
    'int bEnableSCC = parseOptionIntValue(value, bSccError);',
    'int sceneCutAwareQp = parseOptionIntValue(value, bSceneCutAwareQpError);',
    'int edgeVarThreshold = parseOptionIntValue(value, bEdgeVarThresholdError);',
    'int frameNumThreads = parseOptionIntValue(value, bFrameNumThreadsError);',
    'int totalFrames = parseOptionIntValue(value, bTotalFramesError);',
    'bVbvBufInitError = !parseOptionDoubleToken(value, std::strlen(value), vbvBufInit);',
    'int threadCount = parseOptionIntValue(value, bThreadCountError);',
    'uint8_t predStructure = parseOptionUint8Value(value, bPredStructureError);',
    'uint8_t useMasteringDisplayColorVolume = parseOptionUint8Value(value, bMasterDisplayError);',
    'uint8_t useNaluFile = parseOptionUint8Value(value, bNaluFileError);',
)


def check_repo(repo_root):
    repo_root = Path(repo_root)
    path = repo_root / TARGET
    if not path.is_file():
        return [(TARGET.as_posix(), 0, 'missing file')]

    text = path.read_text(encoding='utf-8', errors='ignore')
    failures = []
    for snippet in FORBIDDEN_SNIPPETS:
        if snippet in text:
            failures.append((TARGET.as_posix(), 0, f'forbidden checked-parse regression: {snippet}'))
    for snippet in REQUIRED_SNIPPETS:
        if snippet not in text:
            failures.append((TARGET.as_posix(), 0, f'missing checked-parse guardrail: {snippet}'))
    return failures


def main():
    parser = argparse.ArgumentParser(description='Check reviewed checked parse guardrails in common/param.cpp')
    parser.add_argument('repo_root', nargs='?', default='.')
    args = parser.parse_args()

    failures = check_repo(args.repo_root)
    if failures:
        for path, line, message in failures:
            if line:
                print(f'::error file={path},line={line}::{message}')
            else:
                print(f'::error file={path}::{message}')
        raise SystemExit(1)

    print('Checked parse usage validated')


if __name__ == '__main__':
    main()
