#!/usr/bin/env python3
from pathlib import Path

WORKFLOW_DIR = Path('.github/workflows')
ACTION_DIR = Path('.github/actions')
SCAN_HELPER = Path('.github/scripts/cxx20_scan_helpers.sh')
ENSURE_CMAKE4_HELPER = Path('.github/scripts/ensure_cmake4.sh')
ENSURE_LINUX_SANITIZER_TOOLCHAIN_HELPER = Path('.github/scripts/ensure_linux_sanitizer_toolchain.sh')
MP4_SMOKE_HELPER = Path('.github/scripts/mp4_smoke_helpers.sh')
BUILD_PROFILING_HELPER = Path('.github/scripts/build_x265_profiling.sh')
PROFILING_SMOKE_HELPER = Path('.github/scripts/profiling_smoke_package_verify.sh')
VERIFY_CI_ARCHIVE_HELPER = Path('.github/scripts/verify_ci_archive.sh')
CI_7Z_HELPER = Path('.github/scripts/ci_7z.sh')
CI_VERSION_HELPER = Path('.github/scripts/ci_version_helpers.sh')
RELEASE_ASSET_VALIDATOR = Path('.github/scripts/validate_release_assets.sh')
RUNTIME_SMOKE_SUITE = Path('.github/scripts/runtime_smoke_suite.sh')
MP4_SMOKE_SUITE = Path('.github/scripts/mp4_smoke_suite.sh')
PYTHON_CI_GUARD_BUNDLE = Path('.github/scripts/run_python_ci_guard_bundle.py')
SOURCE_TEST_VECTOR_CHECK = Path('.github/scripts/check_source_test_vectors.py')
SOURCE_TEST_VECTOR_TEST = Path('.github/scripts/test_check_source_test_vectors.py')
API_ZONE_OPEN_STAGING_CHECK = Path('.github/scripts/check_api_zone_open_staging.py')
API_ZONE_OPEN_STAGING_TEST = Path('.github/scripts/test_check_api_zone_open_staging.py')
ENCODER_RPU_REPLACE_SAFETY_CHECK = Path('.github/scripts/check_encoder_rpu_replace_safety.py')
ENCODER_RPU_REPLACE_SAFETY_TEST = Path('.github/scripts/test_check_encoder_rpu_replace_safety.py')
RECONFIG_SAVE_ZONE_ROLLBACK_CHECK = Path('.github/scripts/check_reconfig_save_zone_rollback.py')
RECONFIG_SAVE_ZONE_ROLLBACK_TEST = Path('.github/scripts/test_check_reconfig_save_zone_rollback.py')
PARAM_STRING_REPLACE_SAFETY_CHECK = Path('.github/scripts/check_param_string_replace_safety.py')
PARAM_STRING_REPLACE_SAFETY_TEST = Path('.github/scripts/test_check_param_string_replace_safety.py')
CONFIGURE_ZONE_SVT_STAGING_CHECK = Path('.github/scripts/check_configure_zone_svt_staging.py')
CONFIGURE_ZONE_SVT_STAGING_TEST = Path('.github/scripts/test_check_configure_zone_svt_staging.py')
COPY_USER_SEI_STAGING_CHECK = Path('.github/scripts/check_copy_user_sei_staging.py')
COPY_USER_SEI_STAGING_TEST = Path('.github/scripts/test_check_copy_user_sei_staging.py')
ZONE_PARSE_REPLACE_SAFETY_CHECK = Path('.github/scripts/check_zone_parse_replace_safety.py')
ZONE_PARSE_REPLACE_SAFETY_TEST = Path('.github/scripts/test_check_zone_parse_replace_safety.py')
DUP_SIDE_DATA_STAGING_CHECK = Path('.github/scripts/check_dup_side_data_staging.py')
DUP_SIDE_DATA_STAGING_TEST = Path('.github/scripts/test_check_dup_side_data_staging.py')
CPU_NAME_STRDUP_SAFETY_CHECK = Path('.github/scripts/check_cpu_name_strdup_safety.py')
CPU_NAME_STRDUP_SAFETY_TEST = Path('.github/scripts/test_check_cpu_name_strdup_safety.py')
READ_USER_SEI_STAGING_CHECK = Path('.github/scripts/check_read_user_sei_staging.py')
READ_USER_SEI_STAGING_TEST = Path('.github/scripts/test_check_read_user_sei_staging.py')
COPY_PICTURE_STAGING_CHECK = Path('.github/scripts/check_copy_picture_staging.py')
COPY_PICTURE_STAGING_TEST = Path('.github/scripts/test_check_copy_picture_staging.py')
COPY_PARAMS_ZONE_REPLACE_SAFETY_CHECK = Path('.github/scripts/check_copy_params_zone_replace_safety.py')
COPY_PARAMS_ZONE_REPLACE_SAFETY_TEST = Path('.github/scripts/test_check_copy_params_zone_replace_safety.py')
ENCODER_PARAMETERS_OUTPUT_SAFETY_CHECK = Path('.github/scripts/check_encoder_parameters_output_safety.py')
ENCODER_PARAMETERS_OUTPUT_SAFETY_TEST = Path('.github/scripts/test_check_encoder_parameters_output_safety.py')
ENCODER_GET_STATS_SIZE_GUARD_CHECK = Path('.github/scripts/check_encoder_get_stats_size_guard.py')
ENCODER_GET_STATS_SIZE_GUARD_TEST = Path('.github/scripts/test_check_encoder_get_stats_size_guard.py')
DUP_CREATE_ALLOC_GUARDS_CHECK = Path('.github/scripts/check_dup_create_alloc_guards.py')
DUP_CREATE_ALLOC_GUARDS_TEST = Path('.github/scripts/test_check_dup_create_alloc_guards.py')
ABR_ALLOCBUFFERS_QUEUE_GUARDS_CHECK = Path('.github/scripts/check_abr_allocbuffers_queue_guards.py')
ABR_ALLOCBUFFERS_QUEUE_GUARDS_TEST = Path('.github/scripts/test_check_abr_allocbuffers_queue_guards.py')
ENCODE_QUANT_OFFSETS_STAGING_CHECK = Path('.github/scripts/check_encode_quant_offsets_staging.py')
ENCODE_QUANT_OFFSETS_STAGING_TEST = Path('.github/scripts/test_check_encode_quant_offsets_staging.py')
ANALYSIS_INTRA_ALLOC_GUARDS_CHECK = Path('.github/scripts/check_analysis_intra_alloc_guards.py')
ANALYSIS_INTRA_ALLOC_GUARDS_TEST = Path('.github/scripts/test_check_analysis_intra_alloc_guards.py')
ANALYSIS_INTER_ALLOC_GUARDS_CHECK = Path('.github/scripts/check_analysis_inter_alloc_guards.py')
ANALYSIS_INTER_ALLOC_GUARDS_TEST = Path('.github/scripts/test_check_analysis_inter_alloc_guards.py')
ANALYSIS_INTER_MOTION_ALLOC_GUARDS_CHECK = Path('.github/scripts/check_analysis_inter_motion_alloc_guards.py')
ANALYSIS_INTER_MOTION_ALLOC_GUARDS_TEST = Path('.github/scripts/test_check_analysis_inter_motion_alloc_guards.py')
ANALYSIS_INTER_TEMP_LUMA_ALLOC_GUARD_CHECK = Path('.github/scripts/check_analysis_inter_temp_luma_alloc_guard.py')
ANALYSIS_INTER_TEMP_LUMA_ALLOC_GUARD_TEST = Path('.github/scripts/test_check_analysis_inter_temp_luma_alloc_guard.py')
ANALYSIS_INTER_DEPTH_RUN_GUARD_CHECK = Path('.github/scripts/check_analysis_inter_depth_run_guard.py')
ANALYSIS_INTER_DEPTH_RUN_GUARD_TEST = Path('.github/scripts/test_check_analysis_inter_depth_run_guard.py')
ANALYSIS_CACHE_COST_GUARDS_CHECK = Path('.github/scripts/check_analysis_cache_cost_guards.py')
ANALYSIS_CACHE_COST_GUARDS_TEST = Path('.github/scripts/test_check_analysis_cache_cost_guards.py')
SCALED_ANALYSIS_LOAD_ALLOC_GUARDS_CHECK = Path('.github/scripts/check_scaled_analysis_load_alloc_guards.py')
SCALED_ANALYSIS_LOAD_ALLOC_GUARDS_TEST = Path('.github/scripts/test_check_scaled_analysis_load_alloc_guards.py')
ANALYSIS_2PASS_LOAD_CLEANUP_CHECK = Path('.github/scripts/check_analysis_2pass_load_cleanup.py')
ANALYSIS_2PASS_LOAD_CLEANUP_TEST = Path('.github/scripts/test_check_analysis_2pass_load_cleanup.py')
PICYUV_OFFSET_ROLLBACK_CHECK = Path('.github/scripts/check_picyuv_offset_rollback.py')
PICYUV_OFFSET_ROLLBACK_TEST = Path('.github/scripts/test_check_picyuv_offset_rollback.py')
MOTION_REFERENCE_INIT_GUARDS_CHECK = Path('.github/scripts/check_motion_reference_init_guards.py')
MOTION_REFERENCE_INIT_GUARDS_TEST = Path('.github/scripts/test_check_motion_reference_init_guards.py')
MOTION_SEA_SCRATCH_GUARD_CHECK = Path('.github/scripts/check_motion_sea_scratch_guard.py')
MOTION_SEA_SCRATCH_GUARD_TEST = Path('.github/scripts/test_check_motion_sea_scratch_guard.py')
SCALER_SLICE_LINEBUF_INIT_CHECK = Path('.github/scripts/check_scaler_slice_linebuf_init.py')
SCALER_SLICE_LINEBUF_INIT_TEST = Path('.github/scripts/test_check_scaler_slice_linebuf_init.py')
ANALYSIS_LOAD_STAGING_CLEANUP_CHECK = Path('.github/scripts/check_analysis_load_staging_cleanup.py')
ANALYSIS_LOAD_STAGING_CLEANUP_TEST = Path('.github/scripts/test_check_analysis_load_staging_cleanup.py')
CLI_INPUTFN_ALLOC_GUARD_CHECK = Path('.github/scripts/check_cli_inputfn_alloc_guard.py')
CLI_INPUTFN_ALLOC_GUARD_TEST = Path('.github/scripts/test_check_cli_inputfn_alloc_guard.py')
READ_USER_SEI_CLEANUP_CHECK = Path('.github/scripts/check_read_user_sei_cleanup.py')
READ_USER_SEI_CLEANUP_TEST = Path('.github/scripts/test_check_read_user_sei_cleanup.py')
DEPENDENCY_SUFFIX_CHECK = Path('.github/scripts/check_dependency_patch_suffixes.py')
WINDOWS_DEPS_ACTION = Path('.github/actions/setup-windows-deps/action.yml')
UPDATE_DEPS_WORKFLOW = Path('.github/workflows/update-deps.yml')
BUILD_WORKFLOW = Path('.github/workflows/build.yml')
BUILD_PROFILING_WORKFLOW = Path('.github/workflows/build-profiling.yml')
BUILD_PGO_WORKFLOW = Path('.github/workflows/build-pgo.yml')
BUILD_PROFILING_ACTION = Path('.github/actions/build-x265-profiling/action.yml')

UPDATE_DEPS_ANCHORS = (
    'ffmpeg-ref',
    'mimalloc-ref',
    'obuparse-ref',
    'lsmash-ref',
    'lsmash-cache-suffix',
    'gop-muxer-ref',
    'gop-muxer-cache-suffix',
)
REQUIRED_BUILD_PROFILING_ACTION_SNIPPETS = (
    'bash "${{ github.action_path }}/../../scripts/build_x265_profiling.sh"',
    '"${{ inputs.target-cpu }}"',
    '"${{ inputs.use-mimalloc }}"',
    '"${{ inputs.source-dir }}"',
    '"${{ inputs.build-prefix-path }}"',
    '"${{ inputs.profiling-cxx-flags }}"',
    '"${{ inputs.output-name }}"',
    '"${{ inputs.enable-lsmash }}"',
)
REQUIRED_BUILD_PROFILING_HELPER_SNIPPETS = (
    'CXX20_CHECK_SCRIPT="${script_dir}/check_compile_commands.py"',
    '-DENABLE_CXX20_WARNING_SCAN=ON',
    '-DWARNINGS_AS_ERRORS=ON',
    '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON',
    'check_cxx20_commands_profiling build/8b',
    'check_cxx20_commands_profiling build/12b',
    'check_cxx20_commands_profiling build/10b',
    'case "$profile_class" in',
    'enable_lsmash="${8:-false}"',
    "if [ \"$enable_lsmash\" = 'true' ] || [ \"$enable_lsmash\" = 'ON' ]; then",
    'lsmash_args=(-DENABLE_LSMASH=ON)',
)
REQUIRED_CI_VERSION_HELPER_SNIPPETS = (
    'x265_latest_numeric_tag() {',
    'x265_describe_numeric_tag() {',
    'x265_ci_version_from_latest_tag() {',
    'x265_package_version_for_event() {',
    'if [[ "${GITHUB_REF:-}" == refs/tags/[0-9].[0-9]* ]]; then',
    'elif [[ "${GITHUB_REF:-}" == refs/tags/* ]]; then',
    'Release artifacts require a numeric version tag',
    "version=$(git tag --list '[0-9].[0-9]*' --sort=-v:refname | head -n1)",
    'if [ -z "$version" ] && [ -f .git/shallow ]; then',
    'echo "No numeric tag visible in shallow checkout; fetching tag refs" >&2',
    'git fetch --tags origin',
    'echo "::warning::No numeric version tag found; using $version as CI fallback"',
    'for deepen in 32 128 512 2048; do',
    'echo "Deepening checkout by $deepen commits for CI version tag discovery" >&2',
    'git fetch --tags --deepen="$deepen" origin "${GITHUB_REF}"',
    'echo "Falling back to full history for CI version tag discovery" >&2',
    'git fetch --tags --unshallow origin',
    'version="${latest_tag}-g${head_hash}"',
    'version="${head_tag#M}-g${head_hash}"',
    'version="${orig_tag#M}+${distance}-g${head_hash}"',
    "if [ \"${GITHUB_EVENT_NAME:-}\" = 'workflow_dispatch' ] || [[ \"${GITHUB_REF:-}\" == refs/tags/* ]]; then",
)
REQUIRED_RELEASE_ASSET_VALIDATOR_SNIPPETS = (
    'mode="${1:-}"',
    'asset_dir="${2:-release-assets}"',
    'tag_name="${3:-${GITHUB_REF_NAME:-}}"',
    "mapfile -t assets < <(find \"$asset_dir\" -type f -name '*.7z' -printf '%f\\n' | sort)",
    "release_cpus='x86-64 haswell skylake alderlake raptorlake arrowlake znver2 znver3 znver4 znver5'",
    'case "$mode" in',
    'expected_count=10',
    "count_label='release'",
    "prefix='x265'",
    'expected_count=11',
    "count_label='profiling release'",
    "prefix='x265-profiling'",
    'profdata_count=0',
    "echo \"usage: $0 <release|profiling> [asset-dir] [tag-name]\" >&2",
    "printf 'Expected %d %s archives, found %d:\\n' \"$expected_count\" \"$count_label\" \"${#assets[@]}\" >&2",
    "printf '  %s\\n' \"${assets[@]}\" >&2",
    'if [ "$asset" = "${prefix}-win64-${cpu}-clang.${tag_name}.7z" ]; then',
    'case "$mode:$asset" in',
    'profiling:llvm-profdata-win64-clang.*.7z)',
    'profdata_count=$((profdata_count + 1))',
    'echo "Unexpected release archive: $asset" >&2',
    'echo "Unexpected profiling release archive: $asset" >&2',
    'if [ "$mode" = \'profiling\' ] && [ "$profdata_count" -ne 1 ]; then',
    'echo "Expected exactly one llvm-profdata archive, found $profdata_count" >&2',
)
REQUIRED_UPDATE_DEPS_SNIPPETS = (
    'python .github/scripts/run_python_ci_guard_bundle.py --suite update-deps',
    'for anchor in ffmpeg-ref mimalloc-ref obuparse-ref lsmash-ref lsmash-cache-suffix gop-muxer-ref gop-muxer-cache-suffix; do',
    'lsmash_suffix=$(sed -n',
    'gop_muxer_suffix=$(sed -n',
    'Current L-SMASH cache suffix: ${lsmash_suffix}',
    'Current GOP muxer cache suffix: ${gop_muxer_suffix}',
    'Unexpected dependency update diff paths:',
)
REQUIRED_WINDOWS_DEPS_ACTION_SNIPPETS = (
    'case "${MSYSTEM:-}" in',
    'CLANG64) ;;',
    '/clang64/bin/*|/usr/bin/*) ;;',
    'mimalloc=${{ inputs.mimalloc-ref }} enabled=${{ inputs.use-mimalloc }}',
    'cp -R ffmpeg-install/include/. /usr/local/include/',
    'cp -R ffmpeg-install/lib/. /usr/local/lib/',
    'test -d "$dir"',
    'lsmash=${{ inputs.lsmash-repository }}@${{ inputs.lsmash-ref }} suffix=${{ inputs.lsmash-cache-suffix }} patch=${{ inputs.lsmash-patch-path }}',
    'gop_muxer=${{ inputs.gop-muxer-repository }}@${{ inputs.gop-muxer-ref }} suffix=${{ inputs.gop-muxer-cache-suffix }} patch=${{ inputs.gop-muxer-patch-path }}',
    'git -c core.autocrlf=false reset --hard HEAD',
    'git apply --ignore-whitespace --check ${{ inputs.lsmash-patch-path }}',
    "grep -Fq \"LSMASH_4CC( 'h', 'v', 'c', 'C' )\" codecs/hevc.c",
    "grep -Fq 'lsmash_isom_box_type_value' core/box.c",
    'git -c core.autocrlf=false reset --hard HEAD',
    'git apply ${{ inputs.gop-muxer-patch-path }}',
    'c++ -O2 --std=gnu++20 -I/usr/local/include -c gop_muxer.cpp -o gop_muxer.o',
    'install -v "$file" /usr/local/include/mimalloc.h',
    'install -v "$file" /usr/local/lib/libmimalloc.a',
    'test -s /usr/local/include/mimalloc.h',
    'test -s /usr/local/lib/libmimalloc.a',
)
TME_SMOKE_FLAGS = (
    '--threaded-me',
    '--no-wpp',
    '--no-progress',
)
TME_SMOKE_OPTIONS = (
    ('--input', 'smoke_threaded_me.y4m'),
    ('--input-res', '160x90'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--preset', 'medium'),
    ('--pools', '32'),
    ('--frame-threads', '1'),
    ('--output', 'smoke_threaded_me.hevc'),
)
TME_GENERATOR_OPTIONS = (
    ('-i', 'testsrc2=size=160x90:rate=24'),
    ('-frames:v', '16'),
    ('-pix_fmt', 'yuv420p'),
)
TME_STRESS_FLAGS = (
    '--threaded-me',
    '--no-wpp',
    '--no-progress',
)
TME_STRESS_OPTIONS = (
    ('--input', 'smoke_threaded_me_stress.y4m'),
    ('--input-res', '160x90'),
    ('--fps', '24'),
    ('--frames', '2'),
    ('--preset', 'medium'),
    ('--pools', '32'),
    ('--frame-threads', '1'),
)
TME_STRESS_GENERATOR_OPTIONS = (
    ('-i', 'testsrc2=size=160x90:rate=24'),
    ('-frames:v', '2'),
    ('-pix_fmt', 'yuv420p'),
)
MKV_SMOKE_OPTIONS = (
    ('--input', 'smoke_mkv.y4m'),
    ('--input-res', '160x90'),
    ('--fps', '24'),
    ('--frames', '12'),
    ('--output', 'smoke_mkv.mkv'),
)
MKV_GENERATOR_OPTIONS = (
    ('-i', 'testsrc2=size=160x90:rate=24'),
    ('-frames:v', '12'),
    ('-pix_fmt', 'yuv420p'),
)
LAVF_SMOKE_OPTIONS = (
    ('--input', 'smoke_lavf_input.mkv'),
    ('--frames', '12'),
    ('--output', 'smoke_lavf_output.hevc'),
)
LAVF_GENERATOR_OPTIONS = (
    ('-f', 'lavfi'),
    ('-i', 'testsrc2=size=160x90:rate=24'),
    ('-frames:v', '12'),
    ('-pix_fmt', 'yuv420p'),
    ('-c:v', 'ffv1'),
)
GOP_SMOKE_FLAGS = (
    '--no-open-gop',
)
GOP_SMOKE_OPTIONS = (
    ('--input', 'smoke_gop.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '0'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke_gop.gop'),
)
GOP_GENERATOR_OPTIONS = (
    ('-f', 'lavfi'),
    ('-i', 'testsrc2=size=128x72:rate=24'),
    ('-frames:v', '16'),
    ('-pix_fmt', 'yuv420p'),
)
MP4_SMOKE_FLAGS = (
    '--no-open-gop',
)
MP4_SMOKE_OPTIONS = (
    ('--input', 'smoke.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '4'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke.mp4'),
)
MP4_OPEN_GOP_SMOKE_FLAGS = (
    '--open-gop',
)
MP4_OPEN_GOP_SMOKE_OPTIONS = (
    ('--input', 'smoke_open.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '4'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke_open.mp4'),
)
MP4_CRA_SMOKE_FLAGS = (
    '--cra-nal',
)
MP4_CRA_SMOKE_OPTIONS = (
    ('--input', 'smoke_cra.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '0'),
    ('--keyint', '1'),
    ('--min-keyint', '1'),
    ('--output', 'smoke_cra.mp4'),
)
MP4_SINGLE_FRAME_SMOKE_OPTIONS = (
    ('--input', 'smoke_single.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '1'),
    ('--bframes', '0'),
    ('--keyint', '1'),
    ('--min-keyint', '1'),
    ('--output', 'smoke_single.mp4'),
)
MP4_ZERO_FRAMES_SMOKE_OPTIONS = (
    ('--input', 'smoke_zero.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '0'),
    ('--bframes', '0'),
    ('--keyint', '1'),
    ('--min-keyint', '1'),
    ('--output', 'smoke_zero.mp4'),
)
MP4_VUI_SMOKE_OPTIONS = (
    ('--input', 'smoke_vui.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '4'),
    ('--bframes', '0'),
    ('--keyint', '4'),
    ('--min-keyint', '4'),
    ('--sar', '4:3'),
    ('--range', 'limited'),
    ('--colorprim', 'bt709'),
    ('--transfer', 'bt709'),
    ('--colormatrix', 'bt709'),
    ('--output', 'smoke_vui.mp4'),
)
MP4_FRAC_SMOKE_FLAGS = (
    '--no-open-gop',
)
MP4_FRAC_SMOKE_OPTIONS = (
    ('--input', 'smoke_frac.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24000/1001'),
    ('--frames', '24'),
    ('--bframes', '4'),
    ('--keyint', '12'),
    ('--min-keyint', '12'),
    ('--output', 'smoke_frac.mp4'),
)
MP4_BPYRAMID_SMOKE_FLAGS = (
    '--b-pyramid',
    '--no-open-gop',
)
MP4_BPYRAMID_SMOKE_OPTIONS = (
    ('--input', 'smoke_bpyramid.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '4'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke_bpyramid.mp4'),
)
MP4_AUD_SMOKE_FLAGS = (
    '--aud',
)
MP4_AUD_SMOKE_OPTIONS = (
    ('--input', 'smoke_aud.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '4'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke_aud.mp4'),
)
MP4_EOS_SMOKE_FLAGS = (
    '--eos',
    '--eob',
)
MP4_EOS_SMOKE_OPTIONS = (
    ('--input', 'smoke_eos.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '4'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke_eos.mp4'),
)
MP4_RECOVERY_SMOKE_FLAGS = (
    '--no-open-gop',
    '--idr-recovery-sei',
)
MP4_RECOVERY_SMOKE_OPTIONS = (
    ('--input', 'smoke_recovery.y4m'),
    ('--input-res', '128x72'),
    ('--fps', '24'),
    ('--frames', '16'),
    ('--bframes', '0'),
    ('--keyint', '8'),
    ('--min-keyint', '8'),
    ('--output', 'smoke_recovery.mp4'),
)
ZIMG_SMOKE_OPTIONS = (
    ('--input', 'build/cxx20-warning-scan/smoke_zimg.yuv'),
    ('--input-res', '96x96'),
    ('--fps', '1'),
    ('--frames', '1'),
    ('--vf', 'zimg:lanczos(64,64)'),
    ('--output', 'build/cxx20-warning-scan/smoke_zimg.hevc'),
)
LINUX_GCC_SMOKE_OPTIONS = (
    ('--input', 'build/cxx20-linux-gcc-compile-commands/smoke_linux_gcc.yuv'),
    ('--input-res', '64x64'),
    ('--fps', '1'),
    ('--frames', '1'),
    ('--output', 'build/cxx20-linux-gcc-compile-commands/smoke_linux_gcc.hevc'),
)
WARNING_SCAN_SMOKES = (
    (
        '12-bit warning-scan smoke',
        'build/cxx20-warning-scan-12bit/x265.exe',
        (
            ('--input', 'build/cxx20-warning-scan-12bit/smoke_12bit.yuv'),
            ('--input-res', '64x64'),
            ('--input-depth', '12'),
            ('--output-depth', '12'),
            ('--fps', '1'),
            ('--frames', '1'),
            ('--output', 'build/cxx20-warning-scan-12bit/smoke_12bit.hevc'),
        ),
        'test -s build/cxx20-warning-scan-12bit/smoke_12bit.hevc',
    ),
    (
        'shared-library warning-scan smoke',
        'build/cxx20-warning-scan-shared-library/x265.exe',
        (
            ('--input', 'build/cxx20-warning-scan-shared-library/smoke_shared.yuv'),
            ('--input-res', '64x64'),
            ('--fps', '1'),
            ('--frames', '1'),
            ('--output', 'build/cxx20-warning-scan-shared-library/smoke_shared.hevc'),
        ),
        'test -s build/cxx20-warning-scan-shared-library/smoke_shared.hevc',
    ),
    (
        'all-bit-depth warning-scan smoke',
        'build/cxx20-warning-scan-all/x265.exe',
        (
            ('--input', 'build/cxx20-warning-scan-all/smoke_all.yuv'),
            ('--input-res', '64x64'),
            ('--input-depth', '10'),
            ('--output-depth', '10'),
            ('--fps', '1'),
            ('--frames', '1'),
            ('--output', 'build/cxx20-warning-scan-all/smoke_all.hevc'),
        ),
        'test -s build/cxx20-warning-scan-all/smoke_all.hevc',
    ),
)
PR_TRIGGER_PATHS = (
    '.github/workflows/**',
    '.github/actions/**',
    '.github/patches/**',
    '.github/scripts/**',
    '.github/deps-cache.json',
    'source/**',
    'x265Version.txt',
)
PR_SKIPPED_BUILD_JOBS = (
    'cxx20-warning-scan',
    'build-metadata',
    'build',
)


def build_step_requirements():
    return (
        ('validate-ci-guardrails', 'Run Python CI guard bundle', (
            'python .github/scripts/check_ci_guards.py',
            'python .github/scripts/test_check_ci_guards.py',
            'python .github/scripts/test_check_ci_guards_helpers.py',
            'python .github/scripts/test_check_ci_guards_checks.py',
            'python .github/scripts/test_check_ci_guards_data.py',
            'python .github/scripts/check_cmake_cxx20_contract.py source',
            'python .github/scripts/test_check_cmake_cxx20_contract.py',
            'python .github/scripts/check_cli_nullptr_usage.py .',
            'python .github/scripts/test_check_cli_nullptr_usage.py',
            'python .github/scripts/check_cli_volatile_usage.py .',
            'python .github/scripts/test_check_cli_volatile_usage.py',
            'python .github/scripts/test_check_input_framecount_seek_guard.py',
            'python .github/scripts/check_reconplay_start_failure_guard.py .',
            'python .github/scripts/test_check_reconplay_start_failure_guard.py',
            'python .github/scripts/check_threadpool_create_rollback.py .',
            'python .github/scripts/test_check_threadpool_create_rollback.py',
            'python .github/scripts/check_threadpool_start_rollback.py .',
            'python .github/scripts/test_check_threadpool_start_rollback.py',
            'python .github/scripts/check_frameencoder_start_failure_guard.py .',
            'python .github/scripts/test_check_frameencoder_start_failure_guard.py',
            'python .github/scripts/check_threadedme_start_failure_guard.py .',
            'python .github/scripts/test_check_threadedme_start_failure_guard.py',
            'python .github/scripts/check_input_reader_start_failure_guard.py .',
            'python .github/scripts/test_check_input_reader_start_failure_guard.py',
            'python .github/scripts/check_encoder_threadpool_start_failure_guard.py .',
            'python .github/scripts/test_check_encoder_threadpool_start_failure_guard.py',
            'python .github/scripts/check_encoder_open_fail_cleanup.py .',
            'python .github/scripts/test_check_encoder_open_fail_cleanup.py',
            'python .github/scripts/check_lookahead_alloc_guards.py .',
            'python .github/scripts/test_check_lookahead_alloc_guards.py',
            'python .github/scripts/check_frameencoder_init_alloc_guards.py .',
            'python .github/scripts/test_check_frameencoder_init_alloc_guards.py',
            'python .github/scripts/check_bitcost_alloc_guards.py .',
            'python .github/scripts/test_check_bitcost_alloc_guards.py',
            'python .github/scripts/check_scaler_chroma_dims_guard.py .',
            'python .github/scripts/test_check_scaler_chroma_dims_guard.py',
            'python .github/scripts/check_tonemap_payload_safety.py .',
            'python .github/scripts/test_check_tonemap_payload_safety.py',
            'python .github/scripts/check_temporalfilter_alloc_counts.py .',
            'python .github/scripts/test_check_temporalfilter_alloc_counts.py',
            'python .github/scripts/check_frameencoder_substream_alloc_guards.py .',
            'python .github/scripts/test_check_frameencoder_substream_alloc_guards.py',
            'python .github/scripts/check_frameencoder_initialize_geoms_staging.py .',
            'python .github/scripts/test_check_frameencoder_initialize_geoms_staging.py',
            'python .github/scripts/check_frame_create_subsample_staging.py .',
            'python .github/scripts/test_check_frame_create_subsample_staging.py',
            'python .github/scripts/check_frame_create_rowstate_alloc_guards.py .',
            'python .github/scripts/test_check_frame_create_rowstate_alloc_guards.py',
            'python .github/scripts/check_frame_create_mcstf_refpic_guards.py .',
            'python .github/scripts/test_check_frame_create_mcstf_refpic_guards.py',
            'python .github/scripts/check_frame_create_mcstffencpic_guards.py .',
            'python .github/scripts/test_check_frame_create_mcstffencpic_guards.py',
            'python .github/scripts/check_frame_create_top_alloc_guards.py .',
            'python .github/scripts/test_check_frame_create_top_alloc_guards.py',
            'python .github/scripts/check_frame_alloc_encode_data_guards.py .',
            'python .github/scripts/test_check_frame_alloc_encode_data_guards.py',
            'python .github/scripts/check_x265_picture_init_null_guard.py .',
            'python .github/scripts/test_check_x265_picture_init_null_guard.py',
            'python .github/scripts/check_x265_param_default_null_guard.py .',
            'python .github/scripts/test_check_x265_param_default_null_guard.py',
            'python .github/scripts/check_x265_param_default_preset_null_guard.py .',
            'python .github/scripts/test_check_x265_param_default_preset_null_guard.py',
            'python .github/scripts/check_x265_param_parse_null_guard.py .',
            'python .github/scripts/test_check_x265_param_parse_null_guard.py',
            'python .github/scripts/check_x265_param_apply_profile_null_guard.py .',
            'python .github/scripts/test_check_x265_param_apply_profile_null_guard.py',
            'python .github/scripts/check_param_api_null_guards.py .',
            'python .github/scripts/test_check_param_api_null_guards.py',
            'python .github/scripts/check_zone_and_scenecut_param_parse_null_guards.py .',
            'python .github/scripts/test_check_zone_and_scenecut_param_parse_null_guards.py',
            'python .github/scripts/check_analysis_data_api_null_guards.py .',
            'python .github/scripts/test_check_analysis_data_api_null_guards.py',
            'python .github/scripts/check_query_api_output_null_guards.py .',
            'python .github/scripts/test_check_query_api_output_null_guards.py',
            'python .github/scripts/check_x265_dither_image_null_guards.py .',
            'python .github/scripts/test_check_x265_dither_image_null_guards.py',
            'python .github/scripts/check_csvlog_api_null_guards.py .',
            'python .github/scripts/test_check_csvlog_api_null_guards.py',
            'python .github/scripts/test_check_csvlog_fail_state.py',
            'python .github/scripts/check_vmaf_api_null_guards.py .',
            'python .github/scripts/test_check_vmaf_api_null_guards.py',
            'python .github/scripts/check_threadedme_create_guards.py .',
            'python .github/scripts/test_check_threadedme_create_guards.py',
            'python .github/scripts/check_threadpool_windows_numa_affinity_guard.py .',
            'python .github/scripts/test_check_threadpool_windows_numa_affinity_guard.py',
            'python .github/scripts/check_encoder_ctu_info_guards.py .',
            'python .github/scripts/test_check_encoder_ctu_info_guards.py',
            'python .github/scripts/check_encoder_open_alloc_guard.py .',
            'python .github/scripts/test_check_encoder_open_alloc_guard.py',
            'python .github/scripts/check_encoder_create_object_alloc_guards.py .',
            'python .github/scripts/test_check_encoder_create_object_alloc_guards.py',
            'python .github/scripts/check_encoder_create_core_alloc_guards.py .',
            'python .github/scripts/test_check_encoder_create_core_alloc_guards.py',
            'python .github/scripts/check_encoder_encode_frame_alloc_guards.py .',
            'python .github/scripts/test_check_encoder_encode_frame_alloc_guards.py',
            'python .github/scripts/check_encoder_encode_setup_rollback.py .',
            'python .github/scripts/test_check_encoder_encode_setup_rollback.py',
            'python .github/scripts/check_lowres_aqlayer_alloc_guards.py .',
            'python .github/scripts/test_check_lowres_aqlayer_alloc_guards.py',
            'python .github/scripts/check_lowres_histogram_alloc_guards.py .',
            'python .github/scripts/test_check_lowres_histogram_alloc_guards.py',
            'python .github/scripts/check_frame_edge_aq_alloc_guards.py .',
            'python .github/scripts/test_check_frame_edge_aq_alloc_guards.py',
            'python .github/scripts/check_cutree_sharedmem_alloc_guards.py .',
            'python .github/scripts/test_check_cutree_sharedmem_alloc_guards.py',
            'python .github/scripts/check_scaler_helper_alloc_guards.py .',
            'python .github/scripts/test_check_scaler_helper_alloc_guards.py',
            'python .github/scripts/check_lookahead_create_rollback.py .',
            'python .github/scripts/test_check_lookahead_create_rollback.py',
            'python .github/scripts/check_lookahead_tld_yuv_guards.py .',
            'python .github/scripts/test_check_lookahead_tld_yuv_guards.py',
            'python .github/scripts/check_sea_integral_buffer_lifecycle.py .',
            'python .github/scripts/test_check_sea_integral_buffer_lifecycle.py',
            'python .github/scripts/check_vmaf_temp_buffer_cleanup.py .',
            'python .github/scripts/test_check_vmaf_temp_buffer_cleanup.py',
            'python .github/scripts/check_encoder_rps_list_alloc_guard.py .',
            'python .github/scripts/test_check_encoder_rps_list_alloc_guard.py',
            'python .github/scripts/check_encoder_headers_arg_guard.py .',
            'python .github/scripts/test_check_encoder_headers_arg_guard.py',
            'python .github/scripts/check_framedata_create_rollback.py .',
            'python .github/scripts/test_check_framedata_create_rollback.py',
            'python .github/scripts/check_json11_noexcept_usage.py .',
            'python .github/scripts/test_check_json11_noexcept_usage.py',
            'python .github/scripts/check_json11_number_boundary_safety.py .',
            'python .github/scripts/test_check_json11_number_boundary_safety.py',
            'python .github/scripts/check_json11_unicode_escape_parse_safety.py .',
            'python .github/scripts/test_check_json11_unicode_escape_parse_safety.py',
            'python .github/scripts/check_json11_short_int_parse_safety.py .',
            'python .github/scripts/test_check_json11_short_int_parse_safety.py',
            'python .github/scripts/check_json11_slow_float_token_bounds.py .',
            'python .github/scripts/test_check_json11_slow_float_token_bounds.py',
            'python .github/scripts/check_source_null_exception_usage.py .',
            'python .github/scripts/test_check_source_null_exception_usage.py',
            'python .github/scripts/check_temporalfilter_refpic_rollback.py .',
            'python .github/scripts/test_check_temporalfilter_refpic_rollback.py',
            'python .github/scripts/check_temporalfilter_refpic_state_init.py .',
            'python .github/scripts/test_check_temporalfilter_refpic_state_init.py',
            'python .github/scripts/check_temporalfilter_metld_yuv_guards.py .',
            'python .github/scripts/test_check_temporalfilter_metld_yuv_guards.py',
            'python .github/scripts/check_remaining_null_boundaries.py .',
            'python .github/scripts/test_check_remaining_null_boundaries.py',
            'python .github/scripts/check_sao_create_rollback.py .',
            'python .github/scripts/test_check_sao_create_rollback.py',
            'python .github/scripts/check_sao_param_staging.py .',
            'python .github/scripts/test_check_sao_param_staging.py',
            'python .github/scripts/check_dynamic_hdr10_legacy_patterns.py .',
            'python .github/scripts/test_check_dynamic_hdr10_legacy_patterns.py',
            'python .github/scripts/check_hdr10_json_metadata_ownership.py .',
            'python .github/scripts/test_check_hdr10_json_metadata_ownership.py',
            'python .github/scripts/check_source_legacy_patterns.py .',
            'python .github/scripts/test_check_source_legacy_patterns.py',
            'python .github/scripts/check_all_source_legacy_patterns.py .',
            'python .github/scripts/test_check_all_source_legacy_patterns.py',
            'python .github/scripts/check_external_input_atoi_usage.py .',
            'python .github/scripts/test_check_external_input_atoi_usage.py',
            'python .github/scripts/check_lavf_framecount_parse_safety.py .',
            'python .github/scripts/test_check_lavf_framecount_parse_safety.py',
            'python .github/scripts/check_param_checked_parse_usage.py .',
            'python .github/scripts/test_check_param_checked_parse_usage.py',
            'python .github/scripts/check_scenecut_qp_macro_cleanup.py .',
            'python .github/scripts/test_check_scenecut_qp_macro_cleanup.py',
            'python .github/scripts/check_zone_param_macro_cleanup.py .',
            'python .github/scripts/test_check_zone_param_macro_cleanup.py',
            'python .github/scripts/check_param_parse_macro_cleanup.py .',
            'python .github/scripts/test_check_param_parse_macro_cleanup.py',
            'python .github/scripts/check_abr_config_parse_usage.py .',
            'python .github/scripts/test_check_abr_config_parse_usage.py',
            'python .github/scripts/check_abr_allocbuffers_top_guards.py .',
            'python .github/scripts/test_check_abr_allocbuffers_top_guards.py',
            'python .github/scripts/check_abr_allocbuffers_queue_guards.py .',
            'python .github/scripts/test_check_abr_allocbuffers_queue_guards.py',
            'python .github/scripts/check_abr_allocbuffers_partial_cleanup.py .',
            'python .github/scripts/test_check_abr_allocbuffers_partial_cleanup.py',
            'python .github/scripts/check_abr_allocbuffers_readflag_guard.py .',
            'python .github/scripts/test_check_abr_allocbuffers_readflag_guard.py',
            'python .github/scripts/check_abr_allocbuffers_picidx_guard.py .',
            'python .github/scripts/test_check_abr_allocbuffers_picidx_guard.py',
            'python .github/scripts/check_abr_allocbuffers_analysiswrite_guard.py .',
            'python .github/scripts/test_check_abr_allocbuffers_analysiswrite_guard.py',
            'python .github/scripts/check_abr_allocbuffers_analysisread_guard.py .',
            'python .github/scripts/test_check_abr_allocbuffers_analysisread_guard.py',
            'python .github/scripts/check_abr_init_reader_alloc_guard.py .',
            'python .github/scripts/test_check_abr_init_reader_alloc_guard.py',
            'python .github/scripts/check_abr_init_reader_rollback.py .',
            'python .github/scripts/test_check_abr_init_reader_rollback.py',
            'python .github/scripts/check_abr_init_helper_cleanup.py .',
            'python .github/scripts/test_check_abr_init_helper_cleanup.py',
            'python .github/scripts/check_abr_init_output_null_guard.py .',
            'python .github/scripts/test_check_abr_init_output_null_guard.py',
            'python .github/scripts/check_abr_init_filter_null_guard.py .',
            'python .github/scripts/test_check_abr_init_filter_null_guard.py',
            'python .github/scripts/check_abr_init_api_null_guard.py .',
            'python .github/scripts/test_check_abr_init_api_null_guard.py',
            'python .github/scripts/check_abr_start_threads_failure_propagation.py .',
            'python .github/scripts/test_check_abr_start_threads_failure_propagation.py',
            'python .github/scripts/check_encoder_parameters_output_safety.py .',
            'python .github/scripts/test_check_encoder_parameters_output_safety.py',
            'python .github/scripts/check_encoder_get_stats_size_guard.py .',
            'python .github/scripts/test_check_encoder_get_stats_size_guard.py',
            'python .github/scripts/check_abr_thread_output_null_guard.py .',
            'python .github/scripts/test_check_abr_thread_output_null_guard.py',
            'python .github/scripts/check_abr_thread_api_null_guard.py .',
            'python .github/scripts/test_check_abr_thread_api_null_guard.py',
            'python .github/scripts/check_abr_thread_reconplay_alloc_guard.py .',
            'python .github/scripts/test_check_abr_thread_reconplay_alloc_guard.py',
            'python .github/scripts/check_abr_thread_pts_queue_alloc_guard.py .',
            'python .github/scripts/test_check_abr_thread_pts_queue_alloc_guard.py',
            'python .github/scripts/check_abr_thread_fail_output_guard.py .',
            'python .github/scripts/test_check_abr_thread_fail_output_guard.py',
            'python .github/scripts/check_abr_thread_fail_encoder_guard.py .',
            'python .github/scripts/test_check_abr_thread_fail_encoder_guard.py',
            'python .github/scripts/check_abr_readpicture_srcpic_guard.py .',
            'python .github/scripts/test_check_abr_readpicture_srcpic_guard.py',
            'python .github/scripts/check_abr_readpicture_analysis_guard.py .',
            'python .github/scripts/test_check_abr_readpicture_analysis_guard.py',
            'python .github/scripts/check_abr_thread_readpicture_failure_guard.py .',
            'python .github/scripts/test_check_abr_thread_readpicture_failure_guard.py',
            'python .github/scripts/check_abr_copyinfo_src_guard.py .',
            'python .github/scripts/test_check_abr_copyinfo_src_guard.py',
            'python .github/scripts/check_abr_setreuselevel_ref_guard.py .',
            'python .github/scripts/test_check_abr_setreuselevel_ref_guard.py',
            'python .github/scripts/check_abr_primary_param_guards.py .',
            'python .github/scripts/test_check_abr_primary_param_guards.py',
            'python .github/scripts/check_abr_ctor_top_guards.py .',
            'python .github/scripts/test_check_abr_ctor_top_guards.py',
            'python .github/scripts/check_abr_queue_picture_guards.py .',
            'python .github/scripts/test_check_abr_queue_picture_guards.py',
            'python .github/scripts/check_abr_readpicture_analysis_queue_guard.py .',
            'python .github/scripts/test_check_abr_readpicture_analysis_queue_guard.py',
            'python .github/scripts/check_abr_copyinfo_analysis_buffer_guard.py .',
            'python .github/scripts/test_check_abr_copyinfo_analysis_buffer_guard.py',
            'python .github/scripts/check_abr_analysis_slot_wait_guard.py .',
            'python .github/scripts/test_check_abr_analysis_slot_wait_guard.py',
            'python .github/scripts/check_abr_copyinfo_vbv_lookahead_guard.py .',
            'python .github/scripts/test_check_abr_copyinfo_vbv_lookahead_guard.py',
            'python .github/scripts/check_abr_copyinfo_inter_arrays_guard.py .',
            'python .github/scripts/test_check_abr_copyinfo_inter_arrays_guard.py',
            'python .github/scripts/check_abr_copyinfo_intra_arrays_guard.py .',
            'python .github/scripts/test_check_abr_copyinfo_intra_arrays_guard.py',
            'python .github/scripts/check_abr_thread_analysis_read_guard.py .',
            'python .github/scripts/test_check_abr_thread_analysis_read_guard.py',
            'python .github/scripts/check_abr_thread_queue_state_guards.py .',
            'python .github/scripts/test_check_abr_thread_queue_state_guards.py',
            'python .github/scripts/check_abr_counter_state_guards.py .',
            'python .github/scripts/test_check_abr_counter_state_guards.py',
            'python .github/scripts/check_abr_picture_state_guards.py .',
            'python .github/scripts/test_check_abr_picture_state_guards.py',
            'python .github/scripts/check_abr_thread_field_buffer_guard.py .',
            'python .github/scripts/test_check_abr_thread_field_buffer_guard.py',
            'python .github/scripts/check_abr_thread_field_view_usage.py .',
            'python .github/scripts/test_check_abr_thread_field_view_usage.py',
            'python .github/scripts/check_abr_thread_field_layout_guard.py .',
            'python .github/scripts/test_check_abr_thread_field_layout_guard.py',
            'python .github/scripts/check_abr_thread_field_buffer_state_guard.py .',
            'python .github/scripts/test_check_abr_thread_field_buffer_state_guard.py',
            'python .github/scripts/check_abr_thread_field_reuse_guard.py .',
            'python .github/scripts/test_check_abr_thread_field_reuse_guard.py',
            'python .github/scripts/check_abr_thread_field_plane_guard.py .',
            'python .github/scripts/test_check_abr_thread_field_plane_guard.py',
            'python .github/scripts/check_abr_thread_dolby_rpu_eof_guard.py .',
            'python .github/scripts/test_check_abr_thread_dolby_rpu_eof_guard.py',
            'python .github/scripts/check_abr_thread_pic_in_reset_guard.py .',
            'python .github/scripts/test_check_abr_thread_pic_in_reset_guard.py',
            'python .github/scripts/check_abr_thread_multiview_field_guard.py .',
            'python .github/scripts/test_check_abr_thread_multiview_field_guard.py',
            'python .github/scripts/check_abr_thread_multiview_input_guard.py .',
            'python .github/scripts/test_check_abr_thread_multiview_input_guard.py',
            'python .github/scripts/check_abr_thread_recon_write_guard.py .',
            'python .github/scripts/test_check_abr_thread_recon_write_guard.py',
            'python .github/scripts/check_abr_thread_recon_state_guard.py .',
            'python .github/scripts/test_check_abr_thread_recon_state_guard.py',
            'python .github/scripts/check_abr_thread_output_picture_guard.py .',
            'python .github/scripts/test_check_abr_thread_output_picture_guard.py',
            'python .github/scripts/check_abr_thread_layered_recon_guard.py .',
            'python .github/scripts/test_check_abr_thread_layered_recon_guard.py',
            'python .github/scripts/check_abr_thread_dither_input_guard.py .',
            'python .github/scripts/test_check_abr_thread_dither_input_guard.py',
            'python .github/scripts/check_abr_init_result_propagation.py .',
            'python .github/scripts/test_check_abr_init_result_propagation.py',
            'python .github/scripts/check_abr_scaler_videodesc_ownership.py .',
            'python .github/scripts/test_check_abr_scaler_videodesc_ownership.py',
            'python .github/scripts/check_abr_scaler_videodesc_alloc_guard.py .',
            'python .github/scripts/test_check_abr_scaler_videodesc_alloc_guard.py',
            'python .github/scripts/check_abr_scaler_init_failure_handling.py .',
            'python .github/scripts/test_check_abr_scaler_init_failure_handling.py',
            'python .github/scripts/check_scaler_init_rollback.py .',
            'python .github/scripts/test_check_scaler_init_rollback.py',
            'python .github/scripts/check_wavefront_init_rollback.py .',
            'python .github/scripts/test_check_wavefront_init_rollback.py',
            'python .github/scripts/check_nalu_file_parse_usage.py .',
            'python .github/scripts/test_check_nalu_file_parse_usage.py',
            'python .github/scripts/test_check_nalu_file_error_state.py',
            'python .github/scripts/check_scalinglist_parse_usage.py .',
            'python .github/scripts/test_check_scalinglist_parse_usage.py',
            'python .github/scripts/check_ratecontrol_first_pass_parse_usage.py .',
            'python .github/scripts/test_check_ratecontrol_first_pass_parse_usage.py',
            'python .github/scripts/check_recon_basename_parse_usage.py .',
            'python .github/scripts/test_check_recon_basename_parse_usage.py',
            'python .github/scripts/check_cpu_list_parse_usage.py .',
            'python .github/scripts/test_check_cpu_list_parse_usage.py',
            'python .github/scripts/check_threadpool_cpu_frequency_parse_usage.py .',
            'python .github/scripts/test_check_threadpool_cpu_frequency_parse_usage.py',
            'python .github/scripts/check_threadpool_cpu_frequency_tail_guard.py .',
            'python .github/scripts/test_check_threadpool_cpu_frequency_tail_guard.py',
            'python .github/scripts/check_svt_pools_parse_usage.py .',
            'python .github/scripts/test_check_svt_pools_parse_usage.py',
            'python .github/scripts/check_svt_param_storage_replace_safety.py .',
            'python .github/scripts/test_check_svt_param_storage_replace_safety.py',
            'python .github/scripts/check_svt_app_context_staging.py .',
            'python .github/scripts/test_check_svt_app_context_staging.py',
            'python .github/scripts/check_svt_rpu_payload_replace_safety.py .',
            'python .github/scripts/test_check_svt_rpu_payload_replace_safety.py',
            'python .github/scripts/check_api_zone_open_staging.py .',
            'python .github/scripts/test_check_api_zone_open_staging.py',
            'python .github/scripts/check_encoder_rpu_replace_safety.py .',
            'python .github/scripts/test_check_encoder_rpu_replace_safety.py',
            'python .github/scripts/check_reconfig_save_zone_rollback.py .',
            'python .github/scripts/test_check_reconfig_save_zone_rollback.py',
            'python .github/scripts/check_param_string_replace_safety.py .',
            'python .github/scripts/test_check_param_string_replace_safety.py',
            'python .github/scripts/check_configure_zone_svt_staging.py .',
            'python .github/scripts/test_check_configure_zone_svt_staging.py',
            'python .github/scripts/check_copy_user_sei_staging.py .',
            'python .github/scripts/test_check_copy_user_sei_staging.py',
            'python .github/scripts/check_read_user_sei_cleanup.py .',
            'python .github/scripts/test_check_read_user_sei_cleanup.py',
            'python .github/scripts/check_zone_parse_replace_safety.py .',
            'python .github/scripts/test_check_zone_parse_replace_safety.py',
            'python .github/scripts/check_dup_side_data_staging.py .',
            'python .github/scripts/test_check_dup_side_data_staging.py',
            'python .github/scripts/check_cpu_name_strdup_safety.py .',
            'python .github/scripts/test_check_cpu_name_strdup_safety.py',
            'python .github/scripts/check_read_user_sei_staging.py .',
            'python .github/scripts/test_check_read_user_sei_staging.py',
            'python .github/scripts/check_copy_picture_staging.py .',
            'python .github/scripts/test_check_copy_picture_staging.py',
            'python .github/scripts/check_copy_params_zone_replace_safety.py .',
            'python .github/scripts/test_check_copy_params_zone_replace_safety.py',
            'python .github/scripts/check_encoder_parameters_output_safety.py .',
            'python .github/scripts/test_check_encoder_parameters_output_safety.py',
            'python .github/scripts/check_dup_create_alloc_guards.py .',
            'python .github/scripts/test_check_dup_create_alloc_guards.py',
            'python .github/scripts/check_encode_quant_offsets_staging.py .',
            'python .github/scripts/test_check_encode_quant_offsets_staging.py',
            'python .github/scripts/check_analysis_intra_alloc_guards.py .',
            'python .github/scripts/test_check_analysis_intra_alloc_guards.py',
            'python .github/scripts/check_analysis_inter_alloc_guards.py .',
            'python .github/scripts/test_check_analysis_inter_alloc_guards.py',
            'python .github/scripts/check_analysis_inter_motion_alloc_guards.py .',
            'python .github/scripts/test_check_analysis_inter_motion_alloc_guards.py',
            'python .github/scripts/check_analysis_inter_temp_luma_alloc_guard.py .',
            'python .github/scripts/test_check_analysis_inter_temp_luma_alloc_guard.py',
            'python .github/scripts/check_analysis_inter_depth_run_guard.py .',
            'python .github/scripts/test_check_analysis_inter_depth_run_guard.py',
            'python .github/scripts/check_analysis_cache_cost_guards.py .',
            'python .github/scripts/test_check_analysis_cache_cost_guards.py',
            'python .github/scripts/check_scaled_analysis_load_alloc_guards.py .',
            'python .github/scripts/test_check_scaled_analysis_load_alloc_guards.py',
            'python .github/scripts/check_analysis_2pass_load_cleanup.py .',
            'python .github/scripts/test_check_analysis_2pass_load_cleanup.py',
            'python .github/scripts/check_picyuv_offset_rollback.py .',
            'python .github/scripts/test_check_picyuv_offset_rollback.py',
            'python .github/scripts/check_motion_reference_init_guards.py .',
            'python .github/scripts/test_check_motion_reference_init_guards.py',
            'python .github/scripts/check_motionestimate_init_guard.py .',
            'python .github/scripts/test_check_motionestimate_init_guard.py',
            'python .github/scripts/check_motion_sea_scratch_guard.py .',
            'python .github/scripts/test_check_motion_sea_scratch_guard.py',
            'python .github/scripts/check_scaler_slice_linebuf_init.py .',
            'python .github/scripts/test_check_scaler_slice_linebuf_init.py',
            'python .github/scripts/check_analysis_load_staging_cleanup.py .',
            'python .github/scripts/test_check_analysis_load_staging_cleanup.py',
            'python .github/scripts/test_check_analysis_output_fail_state.py',
            'python .github/scripts/check_reader_thread_alloc_guards.py .',
            'python .github/scripts/test_check_reader_thread_alloc_guards.py',
            'python .github/scripts/check_scaler_thread_alloc_guards.py .',
            'python .github/scripts/test_check_scaler_thread_alloc_guards.py',
            'python .github/scripts/check_raw_output_write_guard.py .',
            'python .github/scripts/test_check_raw_output_write_guard.py',
            'python .github/scripts/check_raw_output_fail_state.py .',
            'python .github/scripts/test_check_raw_output_fail_state.py',
            'python .github/scripts/check_gop_output_fail_state.py .',
            'python .github/scripts/test_check_gop_output_fail_state.py',
            'python .github/scripts/check_gop_smart_fwrite_retry_guard.py .',
            'python .github/scripts/test_check_gop_smart_fwrite_retry_guard.py',
            'python .github/scripts/check_y4m_yuv_row_buffer_alloc_guard.py .',
            'python .github/scripts/test_check_y4m_yuv_row_buffer_alloc_guard.py',
            'python .github/scripts/check_output_open_alloc_guards.py .',
            'python .github/scripts/test_check_output_open_alloc_guards.py',
            'python .github/scripts/check_gop_options_fail_state.py .',
            'python .github/scripts/test_check_gop_options_fail_state.py',
            'python .github/scripts/check_gop_close_fail_state.py .',
            'python .github/scripts/test_check_gop_close_fail_state.py',
            'python .github/scripts/check_gop_intermediate_close_state.py .',
            'python .github/scripts/test_check_gop_intermediate_close_state.py',
            'python .github/scripts/check_mkv_output_fail_state.py .',
            'python .github/scripts/test_check_mkv_output_fail_state.py',
            'python .github/scripts/check_mkv_close_fail_state.py .',
            'python .github/scripts/test_check_mkv_close_fail_state.py',
            'python .github/scripts/check_mkv_writer_open_state.py .',
            'python .github/scripts/test_check_mkv_writer_open_state.py',
            'python .github/scripts/check_mkv_writer_close_state.py .',
            'python .github/scripts/test_check_mkv_writer_close_state.py',
            'python .github/scripts/check_mkv_header_cleanup_state.py .',
            'python .github/scripts/test_check_mkv_header_cleanup_state.py',
            'python .github/scripts/check_mp4_header_sei_alloc_guard.py .',
            'python .github/scripts/test_check_mp4_header_sei_alloc_guard.py',
            'python .github/scripts/check_mp4_preflight_close_state.py .',
            'python .github/scripts/test_check_mp4_preflight_close_state.py',
            'python .github/scripts/check_mp4_handle_close_state.py .',
            'python .github/scripts/test_check_mp4_handle_close_state.py',
            'python .github/scripts/check_cli_progress_file_state.py .',
            'python .github/scripts/test_check_cli_progress_file_state.py',
            'python .github/scripts/check_cli_destroy_close_state.py .',
            'python .github/scripts/test_check_cli_destroy_close_state.py',
            'python .github/scripts/check_multiview_parse_close_state.py .',
            'python .github/scripts/test_check_multiview_parse_close_state.py',
            'python .github/scripts/check_abr_parse_cleanup_state.py .',
            'python .github/scripts/test_check_abr_parse_cleanup_state.py',
            'python .github/scripts/check_vmaf_file_cleanup_state.py .',
            'python .github/scripts/test_check_vmaf_file_cleanup_state.py',
            'python .github/scripts/check_vmaf_data_cleanup_state.py .',
            'python .github/scripts/test_check_vmaf_data_cleanup_state.py',
            'python .github/scripts/test_check_vmaf_frame_read_state.py',
            'python .github/scripts/test_check_vmaf_picture_read_failure.py',
            'python .github/scripts/test_check_vmaf_score_failure_propagation.py',
            'python .github/scripts/check_gop_early_close_state.py .',
            'python .github/scripts/test_check_gop_early_close_state.py',
            'python .github/scripts/check_scenecut_qp_cleanup_state.py .',
            'python .github/scripts/test_check_scenecut_qp_cleanup_state.py',
            'python .github/scripts/check_x265_main_cleanup_state.py .',
            'python .github/scripts/test_check_x265_main_cleanup_state.py',
            'python .github/scripts/check_csvlog_reopen_state.py .',
            'python .github/scripts/test_check_csvlog_reopen_state.py',
            'python .github/scripts/check_csvlog_open_state.py .',
            'python .github/scripts/test_check_csvlog_open_state.py',
            'python .github/scripts/check_ratecontrol_destroy_close_state.py .',
            'python .github/scripts/test_check_ratecontrol_destroy_close_state.py',
            'python .github/scripts/test_check_ratecontrol_write_fail_state.py',
            'python .github/scripts/test_check_ratecontrol_cutree_read_fail_state.py',
            'python .github/scripts/check_encoder_destroy_close_state.py .',
            'python .github/scripts/test_check_encoder_destroy_close_state.py',
            'python .github/scripts/check_lambda_file_close_state.py .',
            'python .github/scripts/test_check_lambda_file_close_state.py',
            'python .github/scripts/check_vmaf_encoder_log_close_state.py .',
            'python .github/scripts/test_check_vmaf_encoder_log_close_state.py',
            'python .github/scripts/check_common_slurp_close_state.py .',
            'python .github/scripts/test_check_common_slurp_close_state.py',
            'python .github/scripts/check_common_slurp_size_guard.py .',
            'python .github/scripts/test_check_common_slurp_size_guard.py',
            'python .github/scripts/check_cutree_sharedmem_name_guard.py .',
            'python .github/scripts/test_check_cutree_sharedmem_name_guard.py',
            'python .github/scripts/check_scalinglist_close_state.py .',
            'python .github/scripts/test_check_scalinglist_close_state.py',
            'python .github/scripts/check_reconplay_pclose_state.py .',
            'python .github/scripts/test_check_reconplay_pclose_state.py',
            'python .github/scripts/check_yuv_input_close_state.py .',
            'python .github/scripts/test_check_yuv_input_close_state.py',
            'python .github/scripts/check_y4m_input_close_state.py .',
            'python .github/scripts/test_check_y4m_input_close_state.py',
            'python .github/scripts/check_riscv_cpuinfo_close_state.py .',
            'python .github/scripts/test_check_riscv_cpuinfo_close_state.py',
            'python .github/scripts/check_common_logfile_open_state.py .',
            'python .github/scripts/test_check_common_logfile_open_state.py',
            'python .github/scripts/check_common_logfile_close_state.py .',
            'python .github/scripts/test_check_common_logfile_close_state.py',
            'python .github/scripts/check_raw_close_state.py .',
            'python .github/scripts/test_check_raw_close_state.py',
            'python .github/scripts/check_raw_open_cleanup_state.py .',
            'python .github/scripts/test_check_raw_open_cleanup_state.py',
            'python .github/scripts/check_raw_stdout_flush_state.py .',
            'python .github/scripts/test_check_raw_stdout_flush_state.py',
            'python .github/scripts/check_x265_check_macro_open_state.py .',
            'python .github/scripts/test_check_x265_check_macro_open_state.py',
            'python .github/scripts/check_x265_check_macro_close_state.py .',
            'python .github/scripts/test_check_x265_check_macro_close_state.py',
            'python .github/scripts/check_film_grain_close_state.py .',
            'python .github/scripts/test_check_film_grain_close_state.py',
            'python .github/scripts/check_film_grain_open_state.py .',
            'python .github/scripts/test_check_film_grain_open_state.py',
            'python .github/scripts/check_analysis_open_state.py .',
            'python .github/scripts/test_check_analysis_open_state.py',
            'python .github/scripts/check_analysis_load_open_state.py .',
            'python .github/scripts/test_check_analysis_load_open_state.py',
            'python .github/scripts/check_ratecontrol_stats_open_state.py .',
            'python .github/scripts/test_check_ratecontrol_stats_open_state.py',
            'python .github/scripts/check_cli_config_open_state.py .',
            'python .github/scripts/test_check_cli_config_open_state.py',
            'python .github/scripts/check_cli_help_exit_cleanup.py .',
            'python .github/scripts/test_check_cli_help_exit_cleanup.py',
            'python .github/scripts/check_abr_ladder_open_state.py .',
            'python .github/scripts/test_check_abr_ladder_open_state.py',
            'python .github/scripts/check_abr_help_exit_precedence.py .',
            'python .github/scripts/test_check_abr_help_exit_precedence.py',
            'python .github/scripts/check_lambda_file_open_state.py .',
            'python .github/scripts/test_check_lambda_file_open_state.py',
            'python .github/scripts/check_nalu_file_open_state.py .',
            'python .github/scripts/test_check_nalu_file_open_state.py',
            'python .github/scripts/check_vmaf_input_open_state.py .',
            'python .github/scripts/test_check_vmaf_input_open_state.py',
            'python .github/scripts/check_common_slurp_open_state.py .',
            'python .github/scripts/test_check_common_slurp_open_state.py',
            'python .github/scripts/check_tonemap_file_open_state.py .',
            'python .github/scripts/test_check_tonemap_file_open_state.py',
            'python .github/scripts/check_scalinglist_open_state.py .',
            'python .github/scripts/test_check_scalinglist_open_state.py',
            'python .github/scripts/check_riscv_cpuinfo_open_state.py .',
            'python .github/scripts/test_check_riscv_cpuinfo_open_state.py',
            'python .github/scripts/check_gop_open_state.py .',
            'python .github/scripts/test_check_gop_open_state.py',
            'python .github/scripts/check_gop_cleanup_close_state.py .',
            'python .github/scripts/test_check_gop_cleanup_close_state.py',
            'python .github/scripts/check_x265_fclose_macro_state.py .',
            'python .github/scripts/test_check_x265_fclose_macro_state.py',
            'python .github/scripts/check_reconplay_pipe_fail_state.py .',
            'python .github/scripts/test_check_reconplay_pipe_fail_state.py',
            'python .github/scripts/check_recon_output_stream_state.py .',
            'python .github/scripts/test_check_recon_output_stream_state.py',
            'python .github/scripts/check_recon_finalize_state.py .',
            'python .github/scripts/test_check_recon_finalize_state.py',
            'python .github/scripts/check_cli_input_open_cleanup.py .',
            'python .github/scripts/test_check_cli_input_open_cleanup.py',
            'python .github/scripts/check_cli_input_validation_cleanup.py .',
            'python .github/scripts/test_check_cli_input_validation_cleanup.py',
            'python .github/scripts/check_cli_profile_apply_cleanup.py .',
            'python .github/scripts/test_check_cli_profile_apply_cleanup.py',
            'python .github/scripts/check_cli_recon_basename_cleanup.py .',
            'python .github/scripts/test_check_cli_recon_basename_cleanup.py',
            'python .github/scripts/check_cli_vmaf_recon_preconditions_cleanup.py .',
            'python .github/scripts/test_check_cli_vmaf_recon_preconditions_cleanup.py',
            'python .github/scripts/check_cli_vmaf_format_cleanup.py .',
            'python .github/scripts/test_check_cli_vmaf_format_cleanup.py',
            'python .github/scripts/check_cli_vmaf_input_open_cleanup.py .',
            'python .github/scripts/test_check_cli_vmaf_input_open_cleanup.py',
            'python .github/scripts/check_cli_output_failure_full_cleanup.py .',
            'python .github/scripts/test_check_cli_output_failure_full_cleanup.py',
            'python .github/scripts/check_cli_output_open_cleanup.py .',
            'python .github/scripts/test_check_cli_output_open_cleanup.py',
            'python .github/scripts/check_cli_recon_open_guard.py .',
            'python .github/scripts/test_check_cli_recon_open_guard.py',
            'python .github/scripts/check_cli_inputfn_alloc_guard.py .',
            'python .github/scripts/test_check_cli_inputfn_alloc_guard.py',
            'python .github/scripts/check_cli_deprecated_parallel_log_args.py .',
            'python .github/scripts/test_check_cli_deprecated_parallel_log_args.py',
            'python .github/scripts/check_scenecut_trailing_arg_diagnostics.py .',
            'python .github/scripts/test_check_scenecut_trailing_arg_diagnostics.py',
            'python .github/scripts/check_recon_output_write_guard.py .',
            'python .github/scripts/test_check_recon_output_write_guard.py',
            'python .github/scripts/test_check_y4m_recon_seek_guard.py',
            'python .github/scripts/check_hme_param_sscanf_usage.py .',
            'python .github/scripts/test_check_hme_param_sscanf_usage.py',
            'python .github/scripts/check_masking_strength_scan_usage.py .',
            'python .github/scripts/test_check_masking_strength_scan_usage.py',
            'python .github/scripts/check_lambda_file_parse_usage.py .',
            'python .github/scripts/test_check_lambda_file_parse_usage.py',
            'python .github/scripts/test_check_lambda_file_error_state.py',
            'python .github/scripts/check_lambda_file_failfast.py .',
            'python .github/scripts/test_check_lambda_file_failfast.py',
            'python .github/scripts/check_ratecontrol_stats_parse_usage.py .',
            'python .github/scripts/test_check_ratecontrol_stats_parse_usage.py',
            'python .github/scripts/check_ratecontrol_stats_line_parse_usage.py .',
            'python .github/scripts/test_check_ratecontrol_stats_line_parse_usage.py',
            'python .github/scripts/check_ratecontrol_stats_prefix_parse_usage.py .',
            'python .github/scripts/test_check_ratecontrol_stats_prefix_parse_usage.py',
            'python .github/scripts/check_print_status_progress_guard.py .',
            'python .github/scripts/test_check_print_status_progress_guard.py',
            'python .github/scripts/check_qpfile_parse_usage.py .',
            'python .github/scripts/test_check_qpfile_parse_usage.py',
            'python .github/scripts/test_check_qpfile_error_state.py',
            'python .github/scripts/check_input_filename_copy_usage.py .',
            'python .github/scripts/test_check_input_filename_copy_usage.py',
            'python .github/scripts/check_dolby_vision_rpu_parse_usage.py .',
            'python .github/scripts/test_check_dolby_vision_rpu_parse_usage.py',
            'python .github/scripts/check_vmaf_recon_state_safety.py .',
            'python .github/scripts/test_check_vmaf_recon_state_safety.py',
            'python .github/scripts/check_vmaf_flush_cleanup.py .',
            'python .github/scripts/test_check_vmaf_flush_cleanup.py',
            'python .github/scripts/check_avs_buffer_replace_safety.py .',
            'python .github/scripts/test_check_avs_buffer_replace_safety.py',
            'python .github/scripts/check_lavf_buffer_replace_safety.py .',
            'python .github/scripts/test_check_lavf_buffer_replace_safety.py',
            'python .github/scripts/check_lavf_openfile_cleanup.py .',
            'python .github/scripts/test_check_lavf_openfile_cleanup.py',
            'python .github/scripts/check_vpy_buffer_replace_safety.py .',
            'python .github/scripts/test_check_vpy_buffer_replace_safety.py',
            'python .github/scripts/check_zonefile_parse_usage.py .',
            'python .github/scripts/test_check_zonefile_parse_usage.py',
            'python .github/scripts/check_zonefile_parse_no_exit.py .',
            'python .github/scripts/test_check_zonefile_parse_no_exit.py',
            'python .github/scripts/check_multiview_config_parse_usage.py .',
            'python .github/scripts/test_check_multiview_config_parse_usage.py',
            'python .github/scripts/check_scenecut_aware_qp_config_parse_usage.py .',
            'python .github/scripts/test_check_scenecut_aware_qp_config_parse_usage.py',
            'python .github/scripts/check_cli_config_file_parse_usage.py .',
            'python .github/scripts/test_check_cli_config_file_parse_usage.py',
            'python .github/scripts/check_preset_index_parse_usage.py .',
            'python .github/scripts/test_check_preset_index_parse_usage.py',
            'python .github/scripts/check_svt_deblock_parse_usage.py .',
            'python .github/scripts/test_check_svt_deblock_parse_usage.py',
            'python .github/scripts/check_checked_parse_helper_safety.py .',
            'python .github/scripts/test_check_checked_parse_helper_safety.py',
            'python .github/scripts/check_zimg_token_parse_usage.py .',
            'python .github/scripts/test_check_zimg_token_parse_usage.py',
            'python .github/scripts/check_zimg_init_rollback.py .',
            'python .github/scripts/test_check_zimg_init_rollback.py',
            'python .github/scripts/check_sei_unsigned_token_safety.py .',
            'python .github/scripts/test_check_sei_unsigned_token_safety.py',
            'python .github/scripts/check_ratecontrol_numeric_helper_safety.py .',
            'python .github/scripts/test_check_ratecontrol_numeric_helper_safety.py',
            'python .github/scripts/check_param_double_token_safety.py .',
            'python .github/scripts/test_check_param_double_token_safety.py',
            'python .github/scripts/check_param_bool_numeric_double_safety.py .',
            'python .github/scripts/test_check_param_bool_numeric_double_safety.py',
            'python .github/scripts/check_fps_parse_safety.py .',
            'python .github/scripts/test_check_fps_parse_safety.py',
            'python .github/scripts/check_log_progress_file_parse_safety.py .',
            'python .github/scripts/test_check_log_progress_file_parse_safety.py',
            'python .github/scripts/check_log_level_parse_safety.py .',
            'python .github/scripts/test_check_log_level_parse_safety.py',
            'python .github/scripts/check_level_idc_parse_safety.py .',
            'python .github/scripts/test_check_level_idc_parse_safety.py',
            'python .github/scripts/check_param_uint_token_safety.py .',
            'python .github/scripts/test_check_param_uint_token_safety.py',
            'python .github/scripts/check_param_pair_parse_safety.py .',
            'python .github/scripts/test_check_param_pair_parse_safety.py',
            'python .github/scripts/check_interlace_parse_safety.py .',
            'python .github/scripts/test_check_interlace_parse_safety.py',
            'python .github/scripts/check_rdoq_level_parse_safety.py .',
            'python .github/scripts/test_check_rdoq_level_parse_safety.py',
            'python .github/scripts/check_bool_int_parse_safety.py .',
            'python .github/scripts/test_check_bool_int_parse_safety.py',
            'python .github/scripts/check_param_bool_numeric_int_safety.py .',
            'python .github/scripts/test_check_param_bool_numeric_int_safety.py',
            'python .github/scripts/check_negated_bool_alias_parse_safety.py .',
            'python .github/scripts/test_check_negated_bool_alias_parse_safety.py',
            'python .github/scripts/check_qp_mode_parse_safety.py .',
            'python .github/scripts/test_check_qp_mode_parse_safety.py',
            'python .github/scripts/check_bitrate_mode_parse_safety.py .',
            'python .github/scripts/test_check_bitrate_mode_parse_safety.py',
            'python .github/scripts/check_svt_qp_mode_parse_safety.py .',
            'python .github/scripts/test_check_svt_qp_mode_parse_safety.py',
            'python .github/scripts/check_svt_bitrate_mode_parse_safety.py .',
            'python .github/scripts/test_check_svt_bitrate_mode_parse_safety.py',
            'python .github/scripts/check_svt_constrained_intra_parse_safety.py .',
            'python .github/scripts/test_check_svt_constrained_intra_parse_safety.py',
            'python .github/scripts/check_svt_vui_timing_info_parse_safety.py .',
            'python .github/scripts/test_check_svt_vui_timing_info_parse_safety.py',
            'python .github/scripts/check_svt_hdr_parse_safety.py .',
            'python .github/scripts/test_check_svt_hdr_parse_safety.py',
            'python .github/scripts/check_svt_aud_parse_safety.py .',
            'python .github/scripts/test_check_svt_aud_parse_safety.py',
            'python .github/scripts/check_svt_high_tier_parse_safety.py .',
            'python .github/scripts/test_check_svt_high_tier_parse_safety.py',
            'python .github/scripts/check_svt_compressed_ten_bit_parse_safety.py .',
            'python .github/scripts/test_check_svt_compressed_ten_bit_parse_safety.py',
            'python .github/scripts/check_svt_speed_control_parse_safety.py .',
            'python .github/scripts/test_check_svt_speed_control_parse_safety.py',
            'python .github/scripts/check_svt_fps_in_vps_parse_safety.py .',
            'python .github/scripts/test_check_svt_fps_in_vps_parse_safety.py',
            'python .github/scripts/check_svt_hrd_parse_safety.py .',
            'python .github/scripts/test_check_svt_hrd_parse_safety.py',
            'python .github/scripts/check_svt_vbv_init_parse_safety.py .',
            'python .github/scripts/test_check_svt_vbv_init_parse_safety.py',
            'python .github/scripts/check_svt_input_depth_parse_safety.py .',
            'python .github/scripts/test_check_svt_input_depth_parse_safety.py',
            'python .github/scripts/check_svt_qpmin_parse_safety.py .',
            'python .github/scripts/test_check_svt_qpmin_parse_safety.py',
            'python .github/scripts/check_svt_qpmax_parse_safety.py .',
            'python .github/scripts/test_check_svt_qpmax_parse_safety.py',
            'python .github/scripts/check_svt_rc_lookahead_parse_safety.py .',
            'python .github/scripts/test_check_svt_rc_lookahead_parse_safety.py',
            'python .github/scripts/check_svt_search_width_parse_safety.py .',
            'python .github/scripts/test_check_svt_search_width_parse_safety.py',
            'python .github/scripts/check_svt_search_height_parse_safety.py .',
            'python .github/scripts/test_check_svt_search_height_parse_safety.py',
            'python .github/scripts/check_svt_hierarchical_level_parse_safety.py .',
            'python .github/scripts/test_check_svt_hierarchical_level_parse_safety.py',
            'python .github/scripts/check_svt_base_layer_switch_mode_parse_safety.py .',
            'python .github/scripts/test_check_svt_base_layer_switch_mode_parse_safety.py',
            'python .github/scripts/check_svt_pred_struct_parse_safety.py .',
            'python .github/scripts/test_check_svt_pred_struct_parse_safety.py',
            'python .github/scripts/check_svt_master_display_parse_safety.py .',
            'python .github/scripts/test_check_svt_master_display_parse_safety.py',
            'python .github/scripts/check_svt_nal_buffer_replace_safety.py .',
            'python .github/scripts/test_check_svt_nal_buffer_replace_safety.py',
            'python .github/scripts/check_nal_takecontents_realloc_safety.py .',
            'python .github/scripts/test_check_nal_takecontents_realloc_safety.py',
            'python .github/scripts/check_svt_nalu_file_parse_safety.py .',
            'python .github/scripts/test_check_svt_nalu_file_parse_safety.py',
            'python .github/scripts/check_svt_pools_parse_safety.py .',
            'python .github/scripts/test_check_svt_pools_parse_safety.py',
            'python .github/scripts/check_svt_pools_exclude_both_sockets_guard.py .',
            'python .github/scripts/test_check_svt_pools_exclude_both_sockets_guard.py',
            'python .github/scripts/check_svt_scenecut_parse_safety.py .',
            'python .github/scripts/test_check_svt_scenecut_parse_safety.py',
            'python .github/scripts/check_svt_interlace_parse_safety.py .',
            'python .github/scripts/test_check_svt_interlace_parse_safety.py',
            'python .github/scripts/check_keyint_parse_safety.py .',
            'python .github/scripts/test_check_keyint_parse_safety.py',
            'python .github/scripts/check_rc_lookahead_parse_safety.py .',
            'python .github/scripts/test_check_rc_lookahead_parse_safety.py',
            'python .github/scripts/check_bframes_parse_safety.py .',
            'python .github/scripts/test_check_bframes_parse_safety.py',
            'python .github/scripts/check_min_keyint_parse_safety.py .',
            'python .github/scripts/test_check_min_keyint_parse_safety.py',
            'python .github/scripts/check_ref_parse_safety.py .',
            'python .github/scripts/test_check_ref_parse_safety.py',
            'python .github/scripts/check_merange_parse_safety.py .',
            'python .github/scripts/test_check_merange_parse_safety.py',
            'python .github/scripts/check_rd_parse_safety.py .',
            'python .github/scripts/test_check_rd_parse_safety.py',
            'python .github/scripts/check_aq_mode_parse_safety.py .',
            'python .github/scripts/test_check_aq_mode_parse_safety.py',
            'python .github/scripts/check_subme_parse_safety.py .',
            'python .github/scripts/test_check_subme_parse_safety.py',
            'python .github/scripts/check_rskip_parse_safety.py .',
            'python .github/scripts/test_check_rskip_parse_safety.py',
            'python .github/scripts/check_limit_tu_parse_safety.py .',
            'python .github/scripts/test_check_limit_tu_parse_safety.py',
            'python .github/scripts/check_rdpenalty_parse_safety.py .',
            'python .github/scripts/test_check_rdpenalty_parse_safety.py',
            'python .github/scripts/check_nr_intra_parse_safety.py .',
            'python .github/scripts/test_check_nr_intra_parse_safety.py',
            'python .github/scripts/check_nr_inter_parse_safety.py .',
            'python .github/scripts/test_check_nr_inter_parse_safety.py',
            'python .github/scripts/check_radl_parse_safety.py .',
            'python .github/scripts/test_check_radl_parse_safety.py',
            'python .github/scripts/check_qg_size_parse_safety.py .',
            'python .github/scripts/test_check_qg_size_parse_safety.py',
            'python .github/scripts/check_lookahead_slices_parse_safety.py .',
            'python .github/scripts/test_check_lookahead_slices_parse_safety.py',
            'python .github/scripts/check_lookahead_threads_parse_safety.py .',
            'python .github/scripts/test_check_lookahead_threads_parse_safety.py',
            'python .github/scripts/check_vbv_fullness_parse_safety.py .',
            'python .github/scripts/test_check_vbv_fullness_parse_safety.py',
            'python .github/scripts/check_csv_log_level_parse_safety.py .',
            'python .github/scripts/test_check_csv_log_level_parse_safety.py',
            'python .github/scripts/check_qpmin_parse_safety.py .',
            'python .github/scripts/test_check_qpmin_parse_safety.py',
            'python .github/scripts/check_limit_refs_parse_safety.py .',
            'python .github/scripts/test_check_limit_refs_parse_safety.py',
            'python .github/scripts/check_cbqpoffs_parse_safety.py .',
            'python .github/scripts/test_check_cbqpoffs_parse_safety.py',
            'python .github/scripts/check_crqpoffs_parse_safety.py .',
            'python .github/scripts/test_check_crqpoffs_parse_safety.py',
            'python .github/scripts/check_log2_max_poc_lsb_parse_safety.py .',
            'python .github/scripts/test_check_log2_max_poc_lsb_parse_safety.py',
            'python .github/scripts/check_dup_threshold_parse_safety.py .',
            'python .github/scripts/test_check_dup_threshold_parse_safety.py',
            'python .github/scripts/check_chromaloc_parse_safety.py .',
            'python .github/scripts/test_check_chromaloc_parse_safety.py',
            'python .github/scripts/check_pass_parse_safety.py .',
            'python .github/scripts/test_check_pass_parse_safety.py',
            'python .github/scripts/check_rskip_edge_threshold_parse_safety.py .',
            'python .github/scripts/test_check_rskip_edge_threshold_parse_safety.py',
            'python .github/scripts/check_deblock_parse_safety.py .',
            'python .github/scripts/test_check_deblock_parse_safety.py',
            'python .github/scripts/check_hash_parse_safety.py .',
            'python .github/scripts/test_check_hash_parse_safety.py',
            'python .github/scripts/check_analysis_reuse_refine_parse_safety.py .',
            'python .github/scripts/test_check_analysis_reuse_refine_parse_safety.py',
            'python .github/scripts/check_misc_control_parse_safety.py .',
            'python .github/scripts/test_check_misc_control_parse_safety.py',
            'python .github/scripts/check_psy_scale_parse_safety.py .',
            'python .github/scripts/test_check_psy_scale_parse_safety.py',
            'python .github/scripts/check_qpstep_parse_safety.py .',
            'python .github/scripts/test_check_qpstep_parse_safety.py',
            'python .github/scripts/check_gop_lookahead_parse_safety.py .',
            'python .github/scripts/test_check_gop_lookahead_parse_safety.py',
            'python .github/scripts/check_gop_lookahead_usage_safety.py .',
            'python .github/scripts/test_check_gop_lookahead_usage_safety.py',
            'python .github/scripts/check_zonefile_startframe_safety.py .',
            'python .github/scripts/test_check_zonefile_startframe_safety.py',
            'python .github/scripts/check_reconfig_window_size_safety.py .',
            'python .github/scripts/test_check_reconfig_window_size_safety.py',
            'python .github/scripts/test_check_no_reset_zone_prefill_guard.py',
            'python .github/scripts/check_scenecut_aware_qp_parse_safety.py .',
            'python .github/scripts/test_check_scenecut_aware_qp_parse_safety.py',
            'python .github/scripts/check_selective_sao_parse_safety.py .',
            'python .github/scripts/test_check_selective_sao_parse_safety.py',
            'python .github/scripts/check_atc_sei_parse_safety.py .',
            'python .github/scripts/test_check_atc_sei_parse_safety.py',
            'python .github/scripts/check_pic_struct_parse_safety.py .',
            'python .github/scripts/test_check_pic_struct_parse_safety.py',
            'python .github/scripts/check_chunk_start_parse_safety.py .',
            'python .github/scripts/test_check_chunk_start_parse_safety.py',
            'python .github/scripts/check_chunk_end_parse_safety.py .',
            'python .github/scripts/test_check_chunk_end_parse_safety.py',
            'python .github/scripts/check_total_frames_parse_safety.py .',
            'python .github/scripts/test_check_total_frames_parse_safety.py',
            'python .github/scripts/check_multiview_scc_parse_safety.py .',
            'python .github/scripts/test_check_multiview_scc_parse_safety.py',
            'python .github/scripts/check_view_layer_limit_safety.py .',
            'python .github/scripts/test_check_view_layer_limit_safety.py',
            'python .github/scripts/check_uint32_token_parse_safety.py .',
            'python .github/scripts/test_check_uint32_token_parse_safety.py',
            'python .github/scripts/check_strict_cbr_parse_safety.py .',
            'python .github/scripts/test_check_strict_cbr_parse_safety.py',
            'python .github/scripts/check_ssim_rd_parse_safety.py .',
            'python .github/scripts/test_check_ssim_rd_parse_safety.py',
            'python .github/scripts/check_sar_parse_safety.py .',
            'python .github/scripts/test_check_sar_parse_safety.py',
            'python .github/scripts/check_hme_parse_safety.py .',
            'python .github/scripts/test_check_hme_parse_safety.py',
            'python .github/scripts/check_zones_parse_safety.py .',
            'python .github/scripts/test_check_zones_parse_safety.py',
            'python .github/scripts/check_parse_name_assignment_safety.py .',
            'python .github/scripts/test_check_parse_name_assignment_safety.py',
            'python .github/scripts/check_frame_threads_parse_safety.py .',
            'python .github/scripts/test_check_frame_threads_parse_safety.py',
            'python .github/scripts/check_bframe_bias_parse_safety.py .',
            'python .github/scripts/test_check_bframe_bias_parse_safety.py',
            'python .github/scripts/check_qscale_mode_parse_safety.py .',
            'python .github/scripts/test_check_qscale_mode_parse_safety.py',
            'python .github/scripts/check_temporal_layers_parse_safety.py .',
            'python .github/scripts/test_check_temporal_layers_parse_safety.py',
            'python .github/scripts/check_qpmax_parse_safety.py .',
            'python .github/scripts/test_check_qpmax_parse_safety.py',
            'python .github/scripts/check_vbv_maxrate_parse_safety.py .',
            'python .github/scripts/test_check_vbv_maxrate_parse_safety.py',
            'python .github/scripts/check_vbv_bufsize_parse_safety.py .',
            'python .github/scripts/test_check_vbv_bufsize_parse_safety.py',
            'python .github/scripts/check_slices_parse_safety.py .',
            'python .github/scripts/test_check_slices_parse_safety.py',
            'python .github/scripts/check_ip_pb_ratio_parse_safety.py .',
            'python .github/scripts/test_check_ip_pb_ratio_parse_safety.py',
            'python .github/scripts/check_vbv_end_frame_adjust_safety.py .',
            'python .github/scripts/test_check_vbv_end_frame_adjust_safety.py',
            'python .github/scripts/check_zone_alloc_size_safety.py .',
            'python .github/scripts/test_check_zone_alloc_size_safety.py',
            'python .github/scripts/check_svt_keyint_parse_safety.py .',
            'python .github/scripts/test_check_svt_keyint_parse_safety.py',
            'python .github/scripts/check_svt_frames_to_be_encoded_parse_safety.py .',
            'python .github/scripts/test_check_svt_frames_to_be_encoded_parse_safety.py',
            'python .github/scripts/check_svt_vbv_maxrate_parse_safety.py .',
            'python .github/scripts/test_check_svt_vbv_maxrate_parse_safety.py',
            'python .github/scripts/check_svt_vbv_bufsize_parse_safety.py .',
            'python .github/scripts/test_check_svt_vbv_bufsize_parse_safety.py',
            'python .github/scripts/check_svt_frame_threads_parse_safety.py .',
            'python .github/scripts/test_check_svt_frame_threads_parse_safety.py',
            'python .github/scripts/check_svt_scenecut_parse_safety.py .',
            'python .github/scripts/test_check_svt_scenecut_parse_safety.py',
            'python .github/scripts/check_svt_interlace_parse_safety.py .',
            'python .github/scripts/test_check_svt_interlace_parse_safety.py',
            'python .github/scripts/check_svt_open_gop_parse_safety.py .',
            'python .github/scripts/test_check_svt_open_gop_parse_safety.py',
            'python .github/scripts/check_svt_hme_parse_safety.py .',
            'python .github/scripts/test_check_svt_hme_parse_safety.py',
            'python .github/scripts/check_svt_sao_parse_safety.py .',
            'python .github/scripts/test_check_svt_sao_parse_safety.py',
            'python .github/scripts/check_video_signal_type_preset_parse.py .',
            'python .github/scripts/test_check_video_signal_type_preset_parse.py',
            'python .github/scripts/check_sei_mastering_display_parse.py .',
            'python .github/scripts/test_check_sei_mastering_display_parse.py',
            'python .github/scripts/check_strict_scan_parsing_usage.py .',
            'python .github/scripts/test_check_strict_scan_parsing_usage.py',
            'python .github/scripts/check_reviewed_string_copy_usage.py .',
            'python .github/scripts/test_check_reviewed_string_copy_usage.py',
            'python .github/scripts/check_gnu20_legacy_guard_bundle.py .',
            'python .github/scripts/test_check_gnu20_legacy_guard_bundle.py',
            'python .github/scripts/test_check_compile_commands.py',
            'python .github/scripts/check_source_test_vectors.py source/test',
            'python .github/scripts/test_check_source_test_vectors.py',
            'python .github/scripts/test_check_dependency_patch_suffixes.py',
            'python .github/scripts/check_release_needs.py',
            'python .github/scripts/test_check_release_needs.py',
            'python .github/scripts/test_check_pgo_consume_chain.py',
        )),
        ('validate-deps-cache-suffix', 'Check dependency patch cache suffixes', (
            'python .github/scripts/check_dependency_patch_suffixes.py',
            'python .github/scripts/check_dependency_patch_suffixes.py --before "$before" --after "$after"',
        )),
        ('build-metadata', 'Get Latest Tag', (
            'source .github/scripts/ci_version_helpers.sh',
            'version=$(x265_latest_numeric_tag)',
        )),
        ('build-metadata', 'Get CI Version', (
            'source .github/scripts/ci_version_helpers.sh',
            'version=$(x265_ci_version_from_latest_tag "${{ steps.tag.outputs.version }}")',
        )),
        ('build', 'Compile X265', (
            'check_cxx20_commands_pgo_consume "$build_dir" "$pgo_flag" --min-cpp-commands="$min_cpp_commands"',
            'check_pgo_consume_commands build/8b-lib "$PGO_8B_LIB_FLAG" 50',
            'check_pgo_consume_commands build/12b-lib "$PGO_12B_LIB_FLAG" 50',
            'check_pgo_consume_commands build/all-8b-lib "$PGO_ALL_FLAG" 50',
            'check_pgo_consume_commands build/all-12b-lib "$PGO_ALL_FLAG" 50',
            'check_pgo_consume_commands build/all "$PGO_ALL_FLAG" 60',
        )),
        ('build', 'Runtime Smokes (All CLI)', (
            'bash x265/.github/scripts/runtime_smoke_suite.sh all',
        )),
        ('build', 'MP4 Smokes (All CLI)', (
            'bash x265/.github/scripts/mp4_smoke_suite.sh all',
        )),
        ('build', 'Verify Package Artifact', (
            'expected_count=4',
            'bash x265/.github/scripts/verify_ci_archive.sh x265-release "x265-win64-${{ matrix.target_cpu }}-clang.${{ steps.package_version.outputs.version }}.7z" artifact-check "${{ matrix.target_cpu }}" "$expected_count"',
        )),
        ('build', 'Set Package Version', (
            'source x265/.github/scripts/ci_version_helpers.sh',
            'version=$(x265_package_version_for_event "${{ needs.build-metadata.outputs.latest_tag }}" "${{ needs.build-metadata.outputs.ci_version }}")',
        )),
        ('cxx20-linux-gcc-compile-commands', 'Run Linux GCC C++20 compile command diagnostics', (
            'check_cxx20_commands_gcc build/cxx20-linux-gcc-compile-commands',
        )),
        ('cxx20-warning-scan', 'Run C++20 CLI and dependency warning scans', (
            '-DENABLE_ZIMG=ON',
        )),
        ('cxx20-warning-scan', 'Run C++20 shared and all-bit-depth warning scans', (
            'check_cxx20_commands_clang build/cxx20-warning-scan-shared-library',
        )),
        ('cxx20-gcc-compile-commands', 'Run GCC C++20 compile command diagnostics', (
            'check_cxx20_commands_gcc build/cxx20-gcc-compile-commands',
        )),
    )


def build_workflow_step_requirements():
    requirements = list(build_step_requirements())
    requirements[0] = (
        'validate-ci-guardrails',
        'Run Python CI guard bundle',
        ('python .github/scripts/run_python_ci_guard_bundle.py',),
    )
    return tuple(requirements)


def profiling_step_requirements():
    return (
        ('validate-guardrails', 'Check CI guardrails', (
            'python .github/scripts/run_python_ci_guard_bundle.py --suite profdata',
        )),
        ('build', 'Get Latest Tag', (
            'source .github/scripts/ci_version_helpers.sh',
            'version=$(x265_latest_numeric_tag)',
        )),
        ('build', 'Get CI Version', (
            'source .github/scripts/ci_version_helpers.sh',
            'version=$(x265_ci_version_from_latest_tag "${{ steps.tag.outputs.version }}")',
        )),
        ('build', 'Package LLVM Profdata Tool', (
            'cp "$llvm_profdata" profdata-dist/',
            'strip -s profdata-dist/llvm-profdata.exe',
        )),
        ('build', 'Smoke, Package, and Verify 8b-lib', (
            'TARGET_CPU="${{ matrix.target_cpu }}" bash x265/.github/scripts/profiling_smoke_package_verify.sh 8b-lib',
        )),
        ('build', 'Smoke, Package, and Verify 12b-lib', (
            'TARGET_CPU="${{ matrix.target_cpu }}" bash x265/.github/scripts/profiling_smoke_package_verify.sh 12b-lib',
        )),
        ('build', 'Smoke, Package, and Verify All', (
            'TARGET_CPU="${{ matrix.target_cpu }}" bash x265/.github/scripts/profiling_smoke_package_verify.sh all',
        )),
        ('build', 'Compress Profiling Build', (
            'bash ../x265/.github/scripts/ci_7z.sh a -t7z -mx=9 ../x265-profiling-win64-${{ matrix.target_cpu }}-clang.${{ steps.package_version.outputs.version }}.7z ./*.exe',
        )),
        ('build', 'Compress LLVM Profdata', (
            'bash ../x265/.github/scripts/ci_7z.sh a -t7z -mx=9 ../llvm-profdata-win64-clang.${{ steps.llvm_profdata.outputs.version }}.7z ./*',
        )),
        ('build', 'Set Package Version', (
            'source x265/.github/scripts/ci_version_helpers.sh',
            'version=$(x265_package_version_for_event "${{ steps.tag.outputs.version }}" "${{ steps.ci_version.outputs.version }}")',
        )),
        ('build', 'Verify Profiling Artifact', (
            'bash x265/.github/scripts/verify_ci_archive.sh x265-profiling "x265-profiling-win64-${{ matrix.target_cpu }}-clang.${{ steps.package_version.outputs.version }}.7z" artifact-check-profiling "${{ matrix.target_cpu }}"',
        )),
        ('build', 'Verify LLVM Profdata Artifact', (
            'bash x265/.github/scripts/verify_ci_archive.sh llvm-profdata "llvm-profdata-win64-clang.${{ steps.llvm_profdata.outputs.version }}.7z" artifact-check-profdata',
        )),
    )


def pgo_step_requirements():
    return (
        ('validate-guardrails', 'Check CI guardrails', (
            'python .github/scripts/run_python_ci_guard_bundle.py --suite pgo',
        )),
        ('generate', 'Run PGO Profiling Workload', (
            'check_cxx20_commands_profiling "$profile_build_dir"',
            'llvm-profdata merge -output=../x265.profdata "${profraw_files[@]}"',
            'llvm-profdata show --summary ../x265.profdata || llvm-profdata show --detailed-summary ../x265.profdata',
        )),
        ('generate', 'Push Baseline Profdata to Branch', (
            'profile_target="${{ github.event.inputs.profile_target || \'all\' }}"',
            'copy_if_exists "profiles/0.profdata" "$profiles_dir/1.profdata"',
            'python x265/.github/scripts/check_profdata_metadata.py "$profdata_push_dir/metadata.json"',
            '--expected-target="$profile_target"',
            '--expected-branch="$profdata_branch"',
            '--expected-toolchain="$profdata_toolchain"',
            '--required-ffmpeg-cache-suffix=pgo-v1-clang',
            '--required-obuparse-cache-suffix="$obuparse_cache_suffix"',
            '--required-lsmash-cache-suffix="$lsmash_cache_suffix"',
            '--required-gop-muxer-cache-suffix="$gop_muxer_cache_suffix"',
            '--require-dependency-fields',
            '--require-fresh-slot',
            'git -C "$profdata_push_dir" push origin HEAD:"$profdata_branch"',
        )),
    )
