#!/usr/bin/env python3
import subprocess
import sys
import tempfile
from pathlib import Path


CHECKER = Path(__file__).with_name('check_param_parse_macro_cleanup.py')

# Normalized checker probes used by the coverage scan for param-parse macro cleanup guardrails.
NORMALIZED_PROBES = (
    'missing param parse bool cleanup window',
    'missing param parse extra bool cleanup window',
    'missing param parse cleanup guardrail: ',
    'forbidden param parse macro regression: ',
    'forbidden param parse bool macro regression: ',
)


def write_targets(root, contents):
    for relative, text in contents.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def run_checker(repo_root):
    return subprocess.run(
        [sys.executable, str(CHECKER), str(repo_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )


def expect_pass(result):
    if result.returncode != 0:
        raise AssertionError(result.stdout)


def expect_fail(result, expected):
    if result.returncode == 0:
        raise AssertionError(f'expected failure containing {expected!r}')
    if expected not in result.stdout:
        raise AssertionError(result.stdout)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    '/* internal versions of string-to-int with additional error checking */',
                    '#undef atoi',
                    '#undef atof',
                    '#define atobool(str) (bNameWasBool = true, x265_atobool(str, bError))',
                    'int x265_param_parse(x265_param* p, const char* name, const char* value)',
                    '{',
                    '    OPT("pmode")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bDistributeModeAnalysis = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("pme")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bDistributeMotionEstimation = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("high-tier")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bHighTier = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("allow-non-conformance")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bAllowNonConformance = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rect")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableRectInter = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("amp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableAMP = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("temporal-mvp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTemporalMvp = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("early-skip")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableEarlySkip = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("tskip")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTransformSkip = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("no-tskip-fast")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTSkipFast = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("tskip-fast")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTSkipFast = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("strong-intra-smoothing")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableStrongIntraSmoothing = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("lossless")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bLossless = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("cu-lossless")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bCULossless = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("constrained-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableConstrainedIntra = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("fast-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableFastIntra = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("open-gop")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bOpenGOP = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("intra-refresh")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bIntraRefresh = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("annexb")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bAnnexB = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("repeat-headers")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bRepeatHeaders = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("wpp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWavefront = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("limit-modes")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->limitModes = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("weightp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWeightedPred = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("weightb")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWeightedBiPred = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rd-refine")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableRdRefine = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("signhide")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSignHiding = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("b-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bIntraInBFrames = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("sao")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSAO = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("sao-non-deblock")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bSaoNonDeblocked = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("ssim")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSsim = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("psnr")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnablePsnr = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("aud")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableAccessUnitDelimiters = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("info")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEmitInfoSEI = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("b-pyramid")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bBPyramid = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("hrd")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEmitHRDSEI = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("hevc-aq")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.hevcAq = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("limit-aq1")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.limitAq1 = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rc-grain")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.bEnableGrain = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("cutree")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.cuTree = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("slow-firstpass")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.bEnableSlowFirstPass = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("uhd-bd")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->uhdBluray = x265_atobool(value, bError);',
                    '    }',
                    '        OPT("analyze-src-pics")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bSourceReferenceEstimation = x265_atobool(value, bError);',
                    '        }',
                    '        OPT("vui-timing-info")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bEmitVUITimingInfo = x265_atobool(value, bError);',
                    '        }',
                    '        OPT("vui-hrd-info")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bEmitVUIHRDInfo = x265_atobool(value, bError);',
                    '        }',
                    '}',
                )) + '\n',
            },
        )
        expect_pass(run_checker(root))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    '/* internal versions of string-to-int with additional error checking */',
                    '#undef atoi',
                    '#undef atof',
                    '#define atoi(str) x265_atoi(str, bError)',
                    '#define atof(str) x265_atof(str, bError)',
                    '#define atobool(str) (bNameWasBool = true, x265_atobool(str, bError))',
                    'int x265_param_parse(x265_param* p, const char* name, const char* value)',
                    '{',
                    '    OPT("pmode")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bDistributeModeAnalysis = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("pme")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bDistributeMotionEstimation = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("high-tier")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bHighTier = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("allow-non-conformance")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bAllowNonConformance = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rect")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableRectInter = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("amp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableAMP = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("temporal-mvp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTemporalMvp = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("early-skip")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableEarlySkip = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("tskip")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTransformSkip = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("no-tskip-fast")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTSkipFast = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("tskip-fast")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTSkipFast = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("strong-intra-smoothing")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableStrongIntraSmoothing = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("lossless")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bLossless = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("cu-lossless")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bCULossless = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("constrained-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableConstrainedIntra = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("fast-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableFastIntra = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("open-gop")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bOpenGOP = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("intra-refresh")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bIntraRefresh = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("annexb")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bAnnexB = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("repeat-headers")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bRepeatHeaders = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("wpp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWavefront = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("limit-modes")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->limitModes = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("weightp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWeightedPred = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("weightb")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWeightedBiPred = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rd-refine")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableRdRefine = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("signhide")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSignHiding = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("b-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bIntraInBFrames = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("sao")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSAO = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("sao-non-deblock")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bSaoNonDeblocked = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("ssim")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSsim = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("psnr")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnablePsnr = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("aud")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableAccessUnitDelimiters = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("info")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEmitInfoSEI = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("b-pyramid")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bBPyramid = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("hrd")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEmitHRDSEI = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("hevc-aq")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.hevcAq = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("limit-aq1")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.limitAq1 = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rc-grain")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.bEnableGrain = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("cutree")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.cuTree = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("slow-firstpass")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.bEnableSlowFirstPass = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("uhd-bd")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->uhdBluray = x265_atobool(value, bError);',
                    '    }',
                    '        OPT("analyze-src-pics")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bSourceReferenceEstimation = x265_atobool(value, bError);',
                    '        }',
                    '        OPT("vui-timing-info")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bEmitVUITimingInfo = x265_atobool(value, bError);',
                    '        }',
                    '        OPT("vui-hrd-info")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bEmitVUIHRDInfo = x265_atobool(value, bError);',
                    '        }',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'forbidden param parse macro regression')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    '/* internal versions of string-to-int with additional error checking */',
                    '#undef atoi',
                    '#undef atof',
                    '#define atobool(str) (bNameWasBool = true, x265_atobool(str, bError))',
                    'int x265_param_parse(x265_param* p, const char* name, const char* value)',
                    '{',
                    '    OPT("pmode")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bDistributeModeAnalysis = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("pme")',
                    '    {',
                        '        bNameWasBool = true;',
                    '        p->bDistributeMotionEstimation = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("high-tier")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bHighTier = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("allow-non-conformance")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bAllowNonConformance = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rect") p->bEnableRectInter = atobool(value);',
                    '    OPT("amp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableAMP = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("temporal-mvp") p->bEnableTemporalMvp = atobool(value);',
                    '    OPT("early-skip")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableEarlySkip = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("tskip") p->bEnableTransformSkip = atobool(value);',
                    '    OPT("no-tskip-fast")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTSkipFast = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("tskip-fast")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableTSkipFast = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("strong-intra-smoothing")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableStrongIntraSmoothing = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("lossless") p->bLossless = atobool(value);',
                    '    OPT("cu-lossless")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bCULossless = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("constrained-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableConstrainedIntra = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("fast-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableFastIntra = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("open-gop") p->bOpenGOP = atobool(value);',
                    '    OPT("intra-refresh")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bIntraRefresh = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("annexb") p->bAnnexB = atobool(value);',
                    '    OPT("repeat-headers")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bRepeatHeaders = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("wpp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWavefront = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("limit-modes") p->limitModes = atobool(value);',
                    '    OPT("weightp")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWeightedPred = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("weightb")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableWeightedBiPred = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("rd-refine") p->bEnableRdRefine = atobool(value);',
                    '    OPT("signhide")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSignHiding = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("b-intra")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bIntraInBFrames = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("sao") p->bEnableSAO = atobool(value);',
                    '    OPT("sao-non-deblock")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bSaoNonDeblocked = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("ssim")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnableSsim = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("psnr")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEnablePsnr = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("aud") p->bEnableAccessUnitDelimiters = atobool(value);',
                    '    OPT("info")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEmitInfoSEI = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("b-pyramid")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bBPyramid = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("hrd")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->bEmitHRDSEI = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("hevc-aq")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.hevcAq = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("limit-aq1") p->rc.limitAq1 = atobool(value);',
                    '    OPT("rc-grain")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.bEnableGrain = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("cutree")    p->rc.cuTree = atobool(value);',
                    '    OPT("slow-firstpass")',
                    '    {',
                    '        bNameWasBool = true;',
                    '        p->rc.bEnableSlowFirstPass = x265_atobool(value, bError);',
                    '    }',
                    '    OPT("uhd-bd") p->uhdBluray = atobool(value);',
                    '        OPT("analyze-src-pics")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bSourceReferenceEstimation = x265_atobool(value, bError);',
                    '        }',
                    '        OPT("vui-timing-info")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bEmitVUITimingInfo = x265_atobool(value, bError);',
                    '        }',
                    '        OPT("vui-hrd-info")',
                    '        {',
                    '            bNameWasBool = true;',
                    '            p->bEmitVUIHRDInfo = x265_atobool(value, bError);',
                    '        }',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'forbidden param parse bool macro regression')

    print('param parse macro cleanup tests passed')


if __name__ == '__main__':
    main()
