#!/usr/bin/env python3
import subprocess
import sys
import tempfile
from pathlib import Path


CHECKER = Path(__file__).with_name('check_zonefile_startframe_safety.py')

# Coverage probes used by the scan for zonefile startFrame guardrails.
NORMALIZED_PROBES = (
    'forbidden zonefile startFrame regression: ',
)


def write_targets(root, contents):
    for relative, text in contents.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def run_checker(repo_root):
    return subprocess.run(
        [sys.executable, str(CHECKER), str(repo_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )


def expect_pass(result):
    if result.returncode != 0:
        raise AssertionError(result.stdout)


def expect_fail(result, expected):
    if result.returncode == 0:
        raise AssertionError(f'expected failure containing {expected!r}')
    if expected not in result.stdout:
        raise AssertionError(result.stdout)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'OPT("max-ausize-factor")',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,',
                    '            "Zonefile bitrate must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                        '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '        }',
                    '    }',
                    '}',
                    'CHECK(param->vui.aspectRatioIdc < 0',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.bitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative bitrate\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.vbvMaxBitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative vbv-maxrate\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                    'uint64_t expectedStartFrame = (uint64_t)encoder->m_zoneIndex * activeParam->reconfigWindowSize;',
                    'if (write)',
                    '    expectedStartFrame = (uint64_t)zone->startFrame +',
                    '                         (uint64_t)activeParam->rc.zonefileCount * (uint64_t)activeParam->reconfigWindowSize;',
                    'if (expectedStartFrame > INT_MAX)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration sequence exceeds supported startFrame range\\n");',
                    '    return -1;',
                    '}',
                    'if ((uint64_t)zone_in->startFrame != expectedStartFrame)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires contiguous startFrame sequencing per reconfig window\\n");',
                    '    return -1;',
                    '}',
                    'if (write && (read < write))',
                )) + '\n',
            },
        )
        expect_pass(run_checker(root))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    CHECK(param->rc.zones[i].startFrame <= 0,',
                    '        "Zonefile start frames must be non-negative");',
                    '}',
                    'OPT("radl")',
                    '{',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                )) + '\n',
                'source/encoder/api.cpp': 'if (zone_in->startFrame < 0)\n',
            },
        )
        expect_fail(run_checker(root), 'forbidden zonefile startFrame regression')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '        }',
                    '    }',
                    '}',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'missing zonefile startFrame guardrail: CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '        }',
                    '    }',
                    '}',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'missing zonefile startFrame guardrail: CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,',
                    '            "Zonefile bitrate must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '        }',
                    '    }',
                    '}',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'missing zonefile startFrame guardrail: if (param->bResetZoneConfig)')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '        }',
                    '    }',
                    '}',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.bitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative bitrate\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'missing zonefile startFrame guardrail: CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,',
                    '            "Zonefile bitrate must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '        }',
                    '    }',
                    '}',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.bitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative bitrate\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                    'uint64_t expectedStartFrame = (uint64_t)encoder->m_zoneIndex * activeParam->reconfigWindowSize;',
                    'if (write)',
                    '    expectedStartFrame = (uint64_t)zone->startFrame +',
                    '                         (uint64_t)activeParam->rc.zonefileCount * (uint64_t)activeParam->reconfigWindowSize;',
                    'if (expectedStartFrame > INT_MAX)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration sequence exceeds supported startFrame range\\n");',
                    '    return -1;',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'missing zonefile startFrame guardrail: if ((uint64_t)zone_in->startFrame != expectedStartFrame)')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '        p->radl = radl;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '}',
                    'OPT("max-ausize-factor")',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,',
                    '            "Zonefile bitrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '        }',
                    '    }',
                    '}',
                    'CHECK(param->vui.aspectRatioIdc < 0',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->zoneParam->rc.bitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative bitrate\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.vbvMaxBitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative vbv-maxrate\\n");',
                    '    return -1;',
                    '}',
                    'uint64_t expectedStartFrame = (uint64_t)encoder->m_zoneIndex * activeParam->reconfigWindowSize;',
                    'if (write)',
                    '    expectedStartFrame = (uint64_t)zone->startFrame +',
                    '                         (uint64_t)activeParam->rc.zonefileCount * (uint64_t)activeParam->reconfigWindowSize;',
                    'if (expectedStartFrame > INT_MAX)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration sequence exceeds supported startFrame range\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                    'if ((uint64_t)zone_in->startFrame != expectedStartFrame)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires contiguous startFrame sequencing per reconfig window\\n");',
                    '    return -1;',
                    '}',
                    'if (write && (read < write))',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'Zonefile radl parsing must preserve the reviewed staged parse-and-publish order')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'OPT("max-ausize-factor")',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,',
                    '            "Zonefile bitrate must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '        }',
                    '    }',
                    '}',
                    'CHECK(param->vui.aspectRatioIdc < 0',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.bitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative bitrate\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.vbvMaxBitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative vbv-maxrate\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                    'uint64_t expectedStartFrame = (uint64_t)encoder->m_zoneIndex * activeParam->reconfigWindowSize;',
                    'if (write)',
                    '    expectedStartFrame = (uint64_t)zone->startFrame +',
                    '                         (uint64_t)activeParam->rc.zonefileCount * (uint64_t)activeParam->reconfigWindowSize;',
                    'if (expectedStartFrame > INT_MAX)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration sequence exceeds supported startFrame range\\n");',
                    '    return -1;',
                    '}',
                    'if ((uint64_t)zone_in->startFrame != expectedStartFrame)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires contiguous startFrame sequencing per reconfig window\\n");',
                    '    return -1;',
                    '}',
                    'if (write && (read < write))',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'Zonefile startFrame validation must preserve the reviewed non-negative, alignment, ordering, and effective-start guard sequence')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'OPT("radl")',
                    '{',
                    '    bool bRadlError = false;',
                    '    int radl = parseOptionIntValue(value, bRadlError);',
                    '    bError |= bRadlError;',
                    '    if (!bRadlError)',
                    '        p->radl = radl;',
                    '}',
                    'OPT("max-ausize-factor")',
                    'if (param->rc.zonefileCount && param->rc.zones)',
                    '{',
                    '    for (int i = 0; i < param->rc.zonefileCount; i++)',
                    '    {',
                    '        CHECK(param->rc.zones[i].startFrame < 0,',
                    '            "Zonefile start frames must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->radl < 0 || param->rc.zones[i].zoneParam->radl > param->rc.zones[i].zoneParam->bframes,',
                    '            "Zonefile radl must be between 0 and the configured bframes");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.bitrate < 0,',
                    '            "Zonefile bitrate must be non-negative");',
                    '        CHECK(param->rc.zones[i].zoneParam->rc.vbvMaxBitrate < 0,',
                    '            "Zonefile vbv-maxrate must be non-negative");',
                    '        if (!param->bResetZoneConfig)',
                    '        {',
                    '            CHECK(param->rc.zones[i].startFrame % param->reconfigWindowSize != 0,',
                    '                "Zonefile start frames must align with the reconfig window size");',
                    '        }',
                    '        if (i > 0)',
                    '        {',
                    '            CHECK(param->rc.zones[i - 1].startFrame >= param->rc.zones[i].startFrame,',
                    '                "Zonefile start frames must be strictly increasing");',
                    '            if (param->bResetZoneConfig)',
                    '            {',
                    '                int prevEffectiveStart = param->rc.zones[i - 1].startFrame;',
                    '                prevEffectiveStart += prevEffectiveStart ? param->rc.zones[i - 1].zoneParam->radl : 0;',
                    '                int effectiveStart = param->rc.zones[i].startFrame;',
                    '                effectiveStart += effectiveStart ? param->rc.zones[i].zoneParam->radl : 0;',
                    '                CHECK(prevEffectiveStart >= effectiveStart,',
                    '                    "Zonefile effective start frames must be strictly increasing");',
                    '            }',
                    '        }',
                    '    }',
                    '}',
                    'CHECK(param->vui.aspectRatioIdc < 0',
                )) + '\n',
                'source/encoder/api.cpp': '\n'.join((
                    'if (zone_in->zoneParam->rc.bitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative bitrate\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->startFrame < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative startFrame\\n");',
                    '    return -1;',
                    '}',
                    'if (zone_in->zoneParam->rc.vbvMaxBitrate < 0)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires a non-negative vbv-maxrate\\n");',
                    '    return -1;',
                    '}',
                    'if (activeParam->reconfigWindowSize && (zone_in->startFrame % activeParam->reconfigWindowSize != 0))',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires startFrame alignment with the reconfig window size\\n");',
                    '    return -1;',
                    '}',
                    'uint64_t expectedStartFrame = (uint64_t)encoder->m_zoneIndex * activeParam->reconfigWindowSize;',
                    'if (write)',
                    '    expectedStartFrame = (uint64_t)zone->startFrame +',
                    '                         (uint64_t)activeParam->rc.zonefileCount * (uint64_t)activeParam->reconfigWindowSize;',
                    'if (expectedStartFrame > INT_MAX)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration sequence exceeds supported startFrame range\\n");',
                    '    return -1;',
                    '}',
                    'if ((uint64_t)zone_in->startFrame != expectedStartFrame)',
                    '{',
                    '    x265_log(activeParam, X265_LOG_ERROR, "Zone reconfiguration requires contiguous startFrame sequencing per reconfig window\\n");',
                    '    return -1;',
                    '}',
                    'if (write && (read < write))',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'Zone reconfiguration API checks must preserve the reviewed guard ordering before accepting a new zone startFrame')

    print('Zonefile startFrame safety tests passed')


if __name__ == '__main__':
    main()
