#!/usr/bin/env python3
import subprocess
import sys
import tempfile
from pathlib import Path


CHECKER = Path(__file__).with_name('check_lambda_file_parse_usage.py')

# Coverage probes used by the scan for lambda-file parsing guardrails.
NORMALIZED_PROBES = (
    'forbidden lambda-file parse regression: ',
    'missing lambda-file parse guardrail: ',
    'parseLambdaFile must reinitialize tok and walk delimiter-skipping token boundaries in the reviewed order',
    'parseLambdaFile must parse token text with x265_atof and run the guarded invalid-value close path before returning an error',
    'parseLambdaFile must keep the oversized-table close path ahead of the error return',
)


def write_targets(root, contents):
    for relative, text in contents.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def run_checker(repo_root):
    return subprocess.run(
        [sys.executable, str(CHECKER), str(repo_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )


def expect_pass(result):
    if result.returncode != 0:
        raise AssertionError(result.stdout)


def expect_fail(result, expected):
    if result.returncode == 0:
        raise AssertionError(f'expected failure containing {expected!r}')
    if expected not in result.stdout:
        raise AssertionError(result.stdout)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'bool parseLambdaFile(x265_param* param)',
                    '{',
                    '    FILE *lfn = x265_fopen(param->rc.lambdaFileName, "r");',
                    '    if (!lfn)',
                    '    {',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    else if (ferror(lfn))',
                    '    {',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after open failure\\n");',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    char line[2048];',
                    'char *tok = nullptr, *buf = nullptr;',
                    'char *scan = nullptr;',
                    '    if (!tok)',
                    '    {',
                    '        if (!fgets(line, sizeof(line), lfn))',
                    '        {',
                    '            if (ferror(lfn))',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after read failure\\n");',
                    '                x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '                return true;',
                    '            }',
                    '            if (t < 2)',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after incomplete parse\\n");',
                    '                x265_log(param, X265_LOG_ERROR, "lambda file is incomplete\\n");',
                    '                return true;',
                    '            }',
                    '            else',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after truncated parse\\n");',
                    '                return false;',
                    '            }',
                    '        }',
                    '        /* truncate at first hash */',
                    "        char *hash = strchr(line, '#');",
                    '        if (hash) *hash = 0;',
                    '        buf = line;',
                    '        scan = buf;',
                    '    }',
                    '    tok = nullptr;',
                    '    while (scan && *scan)',
                    '    {',
                    "        while (*scan == ',' || std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (!*scan)',
                    '        {',
                    '            scan = nullptr;',
                    '            break;',
                    '        }',
                    '        tok = scan;',
                    "        while (*scan && *scan != ',' && !std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (*scan)',
                    "            *scan++ = '\\0';",
                    '        break;',
                    '    }',
                    '    if (tok)',
                    '    {',
                    '        bool bValueError = false;',
                    '        value = x265_atof(tok, bValueError);',
                    '        if (!bValueError)',
                    '            break;',
                    '        x265_log(param, X265_LOG_ERROR, "invalid lambda value: %s\\n", tok);',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after invalid value\\n");',
                    '        return true;',
                    '    }',
                    '    while (1);',
                    '    if (t == 2)',
                    '    {',
                    '        x265_log(param, X265_LOG_ERROR, "lambda file contains too many values\\n");',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after oversized table\\n");',
                    '        return true;',
                    '    }',
                    '    table[i] = value;',
                    '    bool closeFailed = ferror(lfn) != 0;',
                    '    if (fclose(lfn))',
                    '        closeFailed = true;',
                    '    if (closeFailed)',
                    '    {',
                    '        x265_log(param, X265_LOG_WARNING, "unable to finalize lambda file state\\n");',
                    '        return true;',
                    '    }',
                    '    return false;',
                    '}',
                    'bool parseMaskingStrength(x265_param* p, const char* value)',
                    '{',
                    '}',
                )) + '\n',
            },
        )
        expect_pass(run_checker(root))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': 'if (tok && sscanf(tok, "%lf", &value) == 1)\n',
            },
        )
        expect_fail(run_checker(root), 'forbidden lambda-file parse regression')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'bool parseLambdaFile(x265_param* param)',
                    '{',
                    '    FILE *lfn = x265_fopen(param->rc.lambdaFileName, "r");',
                    '    if (!lfn)',
                    '    {',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    else if (ferror(lfn))',
                    '    {',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after open failure\\n");',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    char line[2048];',
                    'char *tok = nullptr, *buf = nullptr;',
                    'char *scan = nullptr;',
                    '    if (!tok)',
                    '    {',
                    '        if (!fgets(line, sizeof(line), lfn))',
                    '        {',
                    '            if (ferror(lfn))',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after read failure\\n");',
                    '                x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '                return true;',
                    '            }',
                    '            if (t < 2)',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after incomplete parse\\n");',
                    '                x265_log(param, X265_LOG_ERROR, "lambda file is incomplete\\n");',
                    '                return true;',
                    '            }',
                    '            else',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after truncated parse\\n");',
                    '                return false;',
                    '            }',
                    '        }',
                    '        /* truncate at first hash */',
                    "        char *hash = strchr(line, '#');",
                    '        if (hash) *hash = 0;',
                    '        scan = buf;',
                    '        buf = line;',
                    '    }',
                    '    tok = nullptr;',
                    '    while (scan && *scan)',
                    '    {',
                    "        while (*scan == ',' || std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (!*scan)',
                    '        {',
                    '            scan = nullptr;',
                    '            break;',
                    '        }',
                    '        tok = scan;',
                    "        while (*scan && *scan != ',' && !std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (*scan)',
                    "            *scan++ = '\\0';",
                    '        break;',
                    '    }',
                    '    if (tok)',
                    '    {',
                    '        bool bValueError = false;',
                    '        value = x265_atof(tok, bValueError);',
                    '        if (!bValueError)',
                    '            break;',
                    '        x265_log(param, X265_LOG_ERROR, "invalid lambda value: %s\\n", tok);',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after invalid value\\n");',
                    '        return true;',
                    '    }',
                    '    while (1);',
                    '    if (t == 2)',
                    '    {',
                    '        x265_log(param, X265_LOG_ERROR, "lambda file contains too many values\\n");',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after oversized table\\n");',
                    '        return true;',
                    '    }',
                    '    table[i] = value;',
                    '    bool closeFailed = ferror(lfn) != 0;',
                    '    if (fclose(lfn))',
                    '        closeFailed = true;',
                    '    if (closeFailed)',
                    '    {',
                    '        x265_log(param, X265_LOG_WARNING, "unable to finalize lambda file state\\n");',
                    '        return true;',
                    '    }',
                    '    return false;',
                    '}',
                    'bool parseMaskingStrength(x265_param* p, const char* value)',
                    '{',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'parseLambdaFile must preserve the reviewed line-fetch close branches before hash truncation and scan initialization')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'bool parseLambdaFile(x265_param* param)',
                    '{',
                    '    FILE *lfn = x265_fopen(param->rc.lambdaFileName, "r");',
                    '    if (!lfn)',
                    '    {',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    else if (ferror(lfn))',
                    '    {',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after open failure\\n");',
                    '        char line[2048];',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    'char *tok = nullptr, *buf = nullptr;',
                    'char *scan = nullptr;',
                    '    if (!tok)',
                    '    {',
                    '        if (!fgets(line, sizeof(line), lfn))',
                    '        {',
                    '            if (ferror(lfn))',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after read failure\\n");',
                    '                x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '                return true;',
                    '            }',
                    '            if (t < 2)',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after incomplete parse\\n");',
                    '                x265_log(param, X265_LOG_ERROR, "lambda file is incomplete\\n");',
                    '                return true;',
                    '            }',
                    '            else',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after truncated parse\\n");',
                    '                return false;',
                    '            }',
                    '        }',
                    '        /* truncate at first hash */',
                    "        char *hash = strchr(line, '#');",
                    '        if (hash) *hash = 0;',
                    '        buf = line;',
                    '        scan = buf;',
                    '    }',
                    '    tok = nullptr;',
                    '    while (scan && *scan)',
                    '    {',
                    "        while (*scan == ',' || std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (!*scan)',
                    '        {',
                    '            scan = nullptr;',
                    '            break;',
                    '        }',
                    '        tok = scan;',
                    "        while (*scan && *scan != ',' && !std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (*scan)',
                    "            *scan++ = '\\0';",
                    '        break;',
                    '    }',
                    '    if (tok)',
                    '    {',
                    '        bool bValueError = false;',
                    '        value = x265_atof(tok, bValueError);',
                    '        if (!bValueError)',
                    '            break;',
                    '        x265_log(param, X265_LOG_ERROR, "invalid lambda value: %s\\n", tok);',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after invalid value\\n");',
                    '        return true;',
                    '    }',
                    '    while (1);',
                    '    if (t == 2)',
                    '    {',
                    '        x265_log(param, X265_LOG_ERROR, "lambda file contains too many values\\n");',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after oversized table\\n");',
                    '        return true;',
                    '    }',
                    '    table[i] = value;',
                    '    bool closeFailed = ferror(lfn) != 0;',
                    '    if (fclose(lfn))',
                    '        closeFailed = true;',
                    '    if (closeFailed)',
                    '    {',
                    '        x265_log(param, X265_LOG_WARNING, "unable to finalize lambda file state\\n");',
                    '        return true;',
                    '    }',
                    '    return false;',
                    '}',
                    'bool parseMaskingStrength(x265_param* p, const char* value)',
                    '{',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'parseLambdaFile must keep the open-failure close/log guard ahead of scanner setup')

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        write_targets(
            root,
            {
                'source/common/param.cpp': '\n'.join((
                    'bool parseLambdaFile(x265_param* param)',
                    '{',
                    '    FILE *lfn = x265_fopen(param->rc.lambdaFileName, "r");',
                    '    if (!lfn)',
                    '    {',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    else if (ferror(lfn))',
                    '    {',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after open failure\\n");',
                    '        x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '        return true;',
                    '    }',
                    '    char line[2048];',
                    'char *tok = nullptr, *buf = nullptr;',
                    'char *scan = nullptr;',
                    '    if (!tok)',
                    '    {',
                    '        if (!fgets(line, sizeof(line), lfn))',
                    '        {',
                    '            if (ferror(lfn))',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after read failure\\n");',
                    '                x265_log_file(param, X265_LOG_ERROR, "unable to read lambda file <%s>\\n", param->rc.lambdaFileName);',
                    '                return true;',
                    '            }',
                    '            if (t < 2)',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after incomplete parse\\n");',
                    '                x265_log(param, X265_LOG_ERROR, "lambda file is incomplete\\n");',
                    '                return true;',
                    '            }',
                    '            else',
                    '            {',
                    '                bool closeFailed = ferror(lfn) != 0;',
                    '                if (fclose(lfn))',
                    '                    closeFailed = true;',
                    '                if (closeFailed)',
                    '                    x265_log(param, X265_LOG_WARNING, "unable to close lambda file after truncated parse\\n");',
                    '                return false;',
                    '            }',
                    '        }',
                    '        /* truncate at first hash */',
                    "        char *hash = strchr(line, '#');",
                    '        if (hash) *hash = 0;',
                    '        buf = line;',
                    '        scan = buf;',
                    '    }',
                    '    tok = nullptr;',
                    '    while (scan && *scan)',
                    '    {',
                    "        while (*scan == ',' || std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (!*scan)',
                    '        {',
                    '            scan = nullptr;',
                    '            break;',
                    '        }',
                    '        tok = scan;',
                    "        while (*scan && *scan != ',' && !std::isspace((unsigned char)*scan))",
                    '            scan++;',
                    '        if (*scan)',
                    "            *scan++ = '\\0';",
                    '        break;',
                    '    }',
                    '    if (tok)',
                    '    {',
                    '        bool bValueError = false;',
                    '        value = x265_atof(tok, bValueError);',
                    '        if (!bValueError)',
                    '            break;',
                    '        x265_log(param, X265_LOG_ERROR, "invalid lambda value: %s\\n", tok);',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after invalid value\\n");',
                    '        return true;',
                    '    }',
                    '    while (1);',
                    '    if (t == 2)',
                    '    {',
                    '        x265_log(param, X265_LOG_ERROR, "lambda file contains too many values\\n");',
                    '        bool closeFailed = ferror(lfn) != 0;',
                    '        if (fclose(lfn))',
                    '            closeFailed = true;',
                    '        if (closeFailed)',
                    '            x265_log(param, X265_LOG_WARNING, "unable to close lambda file after oversized table\\n");',
                    '        return true;',
                    '    }',
                    '    table[i] = value;',
                    '    bool closeFailed = ferror(lfn) != 0;',
                    '    if (closeFailed)',
                    '    {',
                    '        x265_log(param, X265_LOG_WARNING, "unable to finalize lambda file state\\n");',
                    '        return true;',
                    '    }',
                    '    if (fclose(lfn))',
                    '        closeFailed = true;',
                    '    return false;',
                    '}',
                    'bool parseMaskingStrength(x265_param* p, const char* value)',
                    '{',
                    '}',
                )) + '\n',
            },
        )
        expect_fail(run_checker(root), 'parseLambdaFile must preserve the reviewed final close/finalize ordering before reporting success')

    print('Lambda-file parse guard tests passed')


if __name__ == '__main__':
    main()
